[tool.pytest.ini_options]
python_files = "test_*.py"

# treat all warnings as errors
filterwarnings = [
  "error",
  """ignore: invalid escape sequence:DeprecationWarning""",
]

[tool.isort]
profile = "black"
combine_as_imports = true

known_classiq = "classiq"
sections = [
  "FUTURE",
  "STDLIB",
  "THIRDPARTY",
  "FIRSTPARTY",
  "CLASSIQ",
  "LOCALFOLDER",
]
