blank_issues_enabled: false
contact_links:
  - name: Have Question?
    url: https://classiq-community.slack.com/join/shared_invite/zt-2s4gsf6gi-m0YIoI80fyzTaIeVBbmSOw#/shared-invite/email
    about: Join Official Slack Community