// Generated by Classiq.
// Classiq version: 0.46.0
// Creation timestamp: 2024-08-23T07:39:14.296315+00:00
// Random seed: 2692085009

OPENQASM 2.0;
include "qelib1.inc";
gate cbitwise_swap_expanded___105 q0,q1,q2,q3,q4,q5,q6 {
  cswap q0,q1,q4;
  cswap q0,q2,q5;
  cswap q0,q3,q6;
}

gate s_operator_1_bitwise_swap q0,q1,q2,q3,q4,q5,q6 {
  cbitwise_swap_expanded___105 q0,q1,q2,q3,q4,q5,q6;
}

gate s_operator_1_edge_oracle_arithmetic_adder_1 q0,q1,q2,q3,q4,q5 {
  cx q3,q0;
}

gate mcx_hybrid_gray_code_maslov15_140141160568208 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140141160566672 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140141160568208 q0,q1;
}

gate s_operator_1_edge_oracle_arithmetic_equal q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140141160566672 q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_adder_0_140138879804688 q0,q1,q2,q3,q4,q5 {
  cx q3,q0;
}

gate s_operator_1_edge_oracle_arithmetic q0,q1,q2,q3,q4,q5,q6 {
  s_operator_0_edge_oracle_arithmetic_adder_0_140138879804688 q0,q1,q2,q3,q4,q5;
  s_operator_1_edge_oracle_arithmetic_equal q0,q6;
  s_operator_1_edge_oracle_arithmetic_adder_1 q0,q1,q2,q3,q4,q5;
}

gate s_operator_1_edge_oracle q0,q1,q2,q3,q4,q5,q6 {
  s_operator_1_edge_oracle_arithmetic q0,q1,q2,q3,q4,q5,q6;
}

gate c_operator_1_statepreparation_15_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_1_statepreparation_15 q0,q1,q2 {
  c_operator_1_statepreparation_15_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_1_zero_diffuzer_7_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138887896400 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140141160571088 q0,q1,q2,q3,q4 {
  r1tof_140138887896400 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138887896400 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140141160564944 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140141160571088 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_7 q0,q1,q2,q3,q4,q5,q6,q7,q8 {
  c_operator_0_zero_diffuzer_0_mcx_0_140141160564944 q0,q1,q2,q6,q8;
  c_operator_1_zero_diffuzer_7_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140141160564944 q0,q1,q2,q6,q7;
}

gate c_operator_1_inplace_prepare_int_13 q0,q1,q2 {
  x q0;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138816421968 q0,q1,q2 {
}

gate c_operator_1_statepreparation_14 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138816421968 q0,q1,q2;
}

gate c_operator_1_statepreparation_13_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_1_statepreparation_13 q0,q1,q2 {
  c_operator_1_statepreparation_13_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_1_zero_diffuzer_6_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140139370423376 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140141160566864 q0,q1,q2,q3,q4 {
  r1tof_140139370423376 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140139370423376 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140141160562896 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140141160566864 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_6 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140141160562896 q0,q1,q2,q8,q7;
  c_operator_1_zero_diffuzer_6_zero_diffuzer_aux_control_name q3,q4,q5,q8,q9;
  c_operator_0_zero_diffuzer_0_mcx_0_140141160562896 q0,q1,q2,q8,q6;
}

gate c_operator_1_inplace_prepare_int_12 q0,q1,q2 {
  x q0;
}

gate c_operator_1_inplace_prepare_int_11 q0,q1,q2 {
  x q1;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138869715920 q0,q1,q2 {
}

gate c_operator_1_statepreparation_12 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138869715920 q0,q1,q2;
}

gate c_operator_1_statepreparation_11_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_1_statepreparation_11 q0,q1,q2 {
  c_operator_1_statepreparation_11_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_1_zero_diffuzer_5_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138816428944 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140141239401488 q0,q1,q2,q3,q4 {
  r1tof_140138816428944 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138816428944 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140141239398224 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140141239401488 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_5 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140141239398224 q0,q1,q2,q8,q6;
  c_operator_1_zero_diffuzer_5_zero_diffuzer_aux_control_name q3,q4,q5,q7,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140141239398224 q0,q1,q2,q8,q9;
}

gate c_operator_1_inplace_prepare_int_10 q0,q1,q2 {
  x q1;
}

gate c_operator_1_inplace_prepare_int_9 q0,q1,q2 {
  x q1;
  x q0;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138903127696 q0,q1,q2 {
}

gate c_operator_1_statepreparation_10 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138903127696 q0,q1,q2;
}

gate c_operator_1_statepreparation_9_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_1_statepreparation_9 q0,q1,q2 {
  c_operator_1_statepreparation_9_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_1_zero_diffuzer_4_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138869705232 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140141239399632 q0,q1,q2,q3,q4 {
  r1tof_140138869705232 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138869705232 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140141239397840 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140141239399632 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_4 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140141239397840 q0,q1,q2,q6,q9;
  c_operator_1_zero_diffuzer_4_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140141239397840 q0,q1,q2,q6,q7;
}

gate c_operator_1_inplace_prepare_int_8 q0,q1,q2 {
  x q0;
  x q1;
}

gate c_operator_1_inplace_prepare_int_7 q0,q1,q2 {
  x q2;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140141239394448 q0,q1,q2 {
}

gate c_operator_1_statepreparation_8 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140141239394448 q0,q1,q2;
}

gate c_operator_1_statepreparation_7_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_1_statepreparation_7 q0,q1,q2 {
  c_operator_1_statepreparation_7_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_1_zero_diffuzer_3_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138891383504 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140138905446096 q0,q1,q2,q3,q4 {
  r1tof_140138891383504 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138891383504 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140138905438992 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140138905446096 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_3 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140138905438992 q0,q1,q2,q8,q9;
  c_operator_1_zero_diffuzer_3_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140138905438992 q0,q1,q2,q8,q7;
}

gate c_operator_1_inplace_prepare_int_6 q0,q1,q2 {
  x q2;
}

gate c_operator_1_inplace_prepare_int_5 q0,q1,q2 {
  x q2;
  x q0;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138905440912 q0,q1,q2 {
}

gate c_operator_1_statepreparation_6 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138905440912 q0,q1,q2;
}

gate c_operator_1_statepreparation_5_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_1_statepreparation_5 q0,q1,q2 {
  c_operator_1_statepreparation_5_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_1_zero_diffuzer_2_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138815803728 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140138886044176 q0,q1,q2,q3,q4 {
  r1tof_140138815803728 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138815803728 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140141230446032 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140138886044176 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_2 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140141230446032 q0,q1,q2,q7,q9;
  c_operator_1_zero_diffuzer_2_zero_diffuzer_aux_control_name q3,q4,q5,q6,q7;
  c_operator_0_zero_diffuzer_0_mcx_0_140141230446032 q0,q1,q2,q7,q8;
}

gate c_operator_1_inplace_prepare_int_4 q0,q1,q2 {
  x q0;
  x q2;
}

gate c_operator_1_inplace_prepare_int_3 q0,q1,q2 {
  x q2;
  x q1;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140141230448912 q0,q1,q2 {
}

gate c_operator_1_statepreparation_4 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140141230448912 q0,q1,q2;
}

gate c_operator_1_statepreparation_3_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_1_statepreparation_3 q0,q1,q2 {
  c_operator_1_statepreparation_3_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_1_zero_diffuzer_1_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138903129744 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140138849962064 q0,q1,q2,q3,q4 {
  r1tof_140138903129744 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138903129744 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140138849966032 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140138849962064 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_1 q0,q1,q2,q3,q4,q5,q6,q7,q8 {
  c_operator_0_zero_diffuzer_0_mcx_0_140138849966032 q0,q1,q2,q8,q7;
  c_operator_1_zero_diffuzer_1_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140138849966032 q0,q1,q2,q8,q7;
}

gate c_operator_1_inplace_prepare_int_2 q0,q1,q2 {
  x q1;
  x q2;
}

gate c_operator_1_inplace_prepare_int_1 q0,q1,q2 {
  x q2;
  x q1;
  x q0;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140139353245840 q0,q1,q2 {
}

gate c_operator_1_statepreparation_2 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140139353245840 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140139353253520 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140139353253520_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140139353253520 q0,q1;
  x q0;
}

gate c_operator_1_statepreparation_1_rygate_1_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140139353253520_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140139353250704 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140139353250704_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140139353250704 q0,q1;
  x q0;
}

gate c_operator_1_statepreparation_1_rygate_1_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140139353250704_o0 q0,q1;
}

gate c_operator_1_statepreparation_1_rygate_1_qinverse q0,q1 {
  ry(-0.1699184547270609) q0;
  c_operator_1_statepreparation_1_rygate_1_qinverse_mcx_0_qinverse q1,q0;
  ry(0.1699184547270609) q0;
  c_operator_1_statepreparation_1_rygate_1_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140139353253392 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140139353253392_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140139353253392 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_1_statepreparation_1_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140139353253392_o0 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140139353253200 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140139353253200_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140139353253200 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_1_statepreparation_1_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140139353253200_o0 q0,q1,q2;
}

gate c_operator_1_statepreparation_1_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/4) q0;
  c_operator_1_statepreparation_1_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/4) q0;
  c_operator_1_statepreparation_1_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_1_statepreparation_1 q0,q1,q2 {
  c_operator_1_statepreparation_1_rygate_0_qinverse q0,q1,q2;
  c_operator_1_statepreparation_1_rygate_1_qinverse q1,q2;
  ry(-0.14334756890536537) q2;
  h q2;
  h q1;
  h q0;
}

gate c_operator_1_zero_diffuzer_0_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138849962512 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140139360898448 q0,q1,q2,q3,q4 {
  r1tof_140138849962512 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138849962512 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140139360901328 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140139360898448 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_0 q0,q1,q2,q3,q4,q5,q6,q7,q8 {
  c_operator_0_zero_diffuzer_0_mcx_0_140139360901328 q0,q1,q2,q6,q8;
  c_operator_1_zero_diffuzer_0_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140139360901328 q0,q1,q2,q6,q7;
}

gate c_operator_1_inplace_prepare_int_0 q0,q1,q2 {
  x q0;
  x q1;
  x q2;
}

gate mcx_hybrid_gray_code_maslov15_140139360895952 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140139360895952_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140139360895952 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_0_statepreparation_0_rygate_2_mcx_0_140139360910672 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140139360895952_o0 q0,q1,q2;
}

gate c_operator_1_statepreparation_0_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_0_rygate_2_mcx_0_140139360910672 q1,q2,q0;
  ry(-pi/4) q0;
  c_operator_0_statepreparation_0_rygate_2_mcx_0_140139360910672 q1,q2,q0;
  ry(pi/4) q0;
}

gate mcx_hybrid_gray_code_maslov15_140138815313872 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140138815313872_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140138815313872 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_0_rygate_1_mcx_0_140138815307984 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140138815313872_o0 q0,q1;
}

gate c_operator_1_statepreparation_0_rygate_1 q0,q1 {
  c_operator_0_statepreparation_0_rygate_1_mcx_0_140138815307984 q1,q0;
  ry(-0.1699184547270609) q0;
  c_operator_0_statepreparation_0_rygate_1_mcx_0_140138815307984 q1,q0;
  ry(0.1699184547270609) q0;
}

gate c_operator_1_statepreparation_0 q0,q1,q2 {
  h q0;
  h q1;
  h q2;
  ry(0.14334756890536537) q2;
  c_operator_1_statepreparation_0_rygate_1 q1,q2;
  c_operator_1_statepreparation_0_rygate_2 q0,q1,q2;
}

gate cbitwise_swap_expanded___54 q0,q1,q2,q3,q4,q5,q6 {
  cswap q0,q1,q4;
  cswap q0,q2,q5;
  cswap q0,q3,q6;
}

gate s_operator_0_bitwise_swap q0,q1,q2,q3,q4,q5,q6 {
  cbitwise_swap_expanded___54 q0,q1,q2,q3,q4,q5,q6;
}

gate s_operator_0_edge_oracle_arithmetic_adder_1 q0,q1,q2,q3,q4,q5 {
  cx q3,q0;
}

gate mcx_hybrid_gray_code_maslov15_140138814328208 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140138814328208 q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0 q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_adder_0 q0,q1,q2,q3,q4,q5 {
  cx q3,q0;
}

gate s_operator_0_edge_oracle_arithmetic q0,q1,q2,q3,q4,q5,q6 {
  s_operator_0_edge_oracle_arithmetic_adder_0 q0,q1,q2,q3,q4,q5;
  s_operator_0_edge_oracle_arithmetic_equal q0,q6;
  s_operator_0_edge_oracle_arithmetic_adder_1 q0,q1,q2,q3,q4,q5;
}

gate s_operator_0_edge_oracle q0,q1,q2,q3,q4,q5,q6 {
  s_operator_0_edge_oracle_arithmetic q0,q1,q2,q3,q4,q5,q6;
}

gate c_operator_0_statepreparation_15_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_0_statepreparation_15 q0,q1,q2 {
  c_operator_0_statepreparation_15_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_0_zero_diffuzer_7_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138709064464 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140138887540240 q0,q1,q2,q3,q4 {
  r1tof_140138709064464 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138709064464 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140138887530512 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140138887540240 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_7 q0,q1,q2,q3,q4,q5,q6,q7,q8 {
  c_operator_0_zero_diffuzer_0_mcx_0_140138887530512 q0,q1,q2,q7,q3;
  c_operator_0_zero_diffuzer_7_zero_diffuzer_aux_control_name q4,q5,q6,q7,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140138887530512 q0,q1,q2,q7,q3;
}

gate c_operator_0_inplace_prepare_int_13 q0,q1,q2 {
  x q0;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138887541456 q0,q1,q2 {
}

gate c_operator_0_statepreparation_14 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138887541456 q0,q1,q2;
}

gate c_operator_0_statepreparation_13_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_0_statepreparation_13 q0,q1,q2 {
  c_operator_0_statepreparation_13_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_0_zero_diffuzer_6_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138814334928 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140141152713808 q0,q1,q2,q3,q4 {
  r1tof_140138814334928 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138814334928 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140141152711888 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140141152713808 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_6 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140141152711888 q0,q1,q2,q9,q3;
  c_operator_0_zero_diffuzer_6_zero_diffuzer_aux_control_name q4,q5,q6,q8,q9;
  c_operator_0_zero_diffuzer_0_mcx_0_140141152711888 q0,q1,q2,q9,q7;
}

gate c_operator_0_inplace_prepare_int_12 q0,q1,q2 {
  x q0;
}

gate c_operator_0_inplace_prepare_int_11 q0,q1,q2 {
  x q1;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138861648784 q0,q1,q2 {
}

gate c_operator_0_statepreparation_12 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138861648784 q0,q1,q2;
}

gate c_operator_0_statepreparation_11_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_0_statepreparation_11 q0,q1,q2 {
  c_operator_0_statepreparation_11_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_0_zero_diffuzer_5_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138909431248 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140141243535888 q0,q1,q2,q3,q4 {
  r1tof_140138909431248 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138909431248 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140141243541136 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140141243535888 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_5 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140141243541136 q0,q1,q2,q7,q3;
  c_operator_0_zero_diffuzer_5_zero_diffuzer_aux_control_name q4,q5,q6,q7,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140141243541136 q0,q1,q2,q7,q9;
}

gate c_operator_0_inplace_prepare_int_10 q0,q1,q2 {
  x q1;
}

gate c_operator_0_inplace_prepare_int_9 q0,q1,q2 {
  x q1;
  x q0;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140141243543248 q0,q1,q2 {
}

gate c_operator_0_statepreparation_10 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140141243543248 q0,q1,q2;
}

gate c_operator_0_statepreparation_9_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_0_statepreparation_9 q0,q1,q2 {
  c_operator_0_statepreparation_9_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_0_zero_diffuzer_4_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140141239864272 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140138899154192 q0,q1,q2,q3,q4 {
  r1tof_140141239864272 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140141239864272 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140138899152592 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140138899154192 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_4 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140138899152592 q0,q1,q2,q7,q8;
  c_operator_0_zero_diffuzer_4_zero_diffuzer_aux_control_name q3,q4,q5,q7,q9;
  c_operator_0_zero_diffuzer_0_mcx_0_140138899152592 q0,q1,q2,q7,q6;
}

gate c_operator_0_inplace_prepare_int_8 q0,q1,q2 {
  x q0;
  x q1;
}

gate c_operator_0_inplace_prepare_int_7 q0,q1,q2 {
  x q2;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138899160656 q0,q1,q2 {
}

gate c_operator_0_statepreparation_8 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138899160656 q0,q1,q2;
}

gate c_operator_0_statepreparation_7_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_0_statepreparation_7 q0,q1,q2 {
  c_operator_0_statepreparation_7_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_0_zero_diffuzer_3_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138814011664 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140138904978704 q0,q1,q2,q3,q4 {
  r1tof_140138814011664 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138814011664 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140138904993168 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140138904978704 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_3 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140138904993168 q0,q1,q2,q6,q7;
  c_operator_0_zero_diffuzer_3_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140138904993168 q0,q1,q2,q6,q9;
}

gate c_operator_0_inplace_prepare_int_6 q0,q1,q2 {
  x q2;
}

gate c_operator_0_inplace_prepare_int_5 q0,q1,q2 {
  x q2;
  x q0;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138904989392 q0,q1,q2 {
}

gate c_operator_0_statepreparation_6 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138904989392 q0,q1,q2;
}

gate c_operator_0_statepreparation_5_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_0_statepreparation_5 q0,q1,q2 {
  c_operator_0_statepreparation_5_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_0_zero_diffuzer_2_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138861652560 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140138899046800 q0,q1,q2,q3,q4 {
  r1tof_140138861652560 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138861652560 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140138899060368 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140138899046800 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_2 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140138899060368 q0,q1,q2,q6,q7;
  c_operator_0_zero_diffuzer_2_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140138899060368 q0,q1,q2,q6,q9;
}

gate c_operator_0_inplace_prepare_int_4 q0,q1,q2 {
  x q0;
  x q2;
}

gate c_operator_0_inplace_prepare_int_3 q0,q1,q2 {
  x q2;
  x q1;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138814714832 q0,q1,q2 {
}

gate c_operator_0_statepreparation_4 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation_140138814714832 q0,q1,q2;
}

gate c_operator_0_statepreparation_3_computationalbasisstatepreparation_qinverse q0,q1,q2 {
}

gate c_operator_0_statepreparation_3 q0,q1,q2 {
  c_operator_0_statepreparation_3_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_0_zero_diffuzer_1_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140138904979216 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140138814714384 q0,q1,q2,q3,q4 {
  r1tof_140138904979216 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140138904979216 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140138814705872 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140138814714384 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_1 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140138814705872 q0,q1,q2,q6,q7;
  c_operator_0_zero_diffuzer_1_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140138814705872 q0,q1,q2,q6,q9;
}

gate c_operator_0_inplace_prepare_int_2 q0,q1,q2 {
  x q1;
  x q2;
}

gate c_operator_0_inplace_prepare_int_1 q0,q1,q2 {
  x q2;
  x q1;
  x q0;
}

gate c_operator_0_statepreparation_2_computationalbasisstatepreparation q0,q1,q2 {
}

gate c_operator_0_statepreparation_2 q0,q1,q2 {
  c_operator_0_statepreparation_2_computationalbasisstatepreparation q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140141160832400 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140141160832400_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140141160832400 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_1_rygate_1_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140141160832400_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140139376787664 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140139376787664_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140139376787664 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_1_rygate_1_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140139376787664_o0 q0,q1;
}

gate c_operator_0_statepreparation_1_rygate_1_qinverse q0,q1 {
  ry(-0.1699184547270609) q0;
  c_operator_0_statepreparation_1_rygate_1_qinverse_mcx_0_qinverse q1,q0;
  ry(0.1699184547270609) q0;
  c_operator_0_statepreparation_1_rygate_1_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140141160375376 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140141160375376_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140141160375376 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_0_statepreparation_1_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140141160375376_o0 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140138896484816 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140138896484816_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140138896484816 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_0_statepreparation_1_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140138896484816_o0 q0,q1,q2;
}

gate c_operator_0_statepreparation_1_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/4) q0;
  c_operator_0_statepreparation_1_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/4) q0;
  c_operator_0_statepreparation_1_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_0_statepreparation_1 q0,q1,q2 {
  c_operator_0_statepreparation_1_rygate_0_qinverse q0,q1,q2;
  c_operator_0_statepreparation_1_rygate_1_qinverse q1,q2;
  ry(-0.14334756890536537) q2;
  h q2;
  h q1;
  h q0;
}

gate c_operator_0_zero_diffuzer_0_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140141160373264 q0,q1,q2,q3,q4 {
  r1tof q0,q1,q4;
  ccx q4,q2,q3;
  r1tof q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140141160373264 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0 q0,q1,q2,q3,q4;
  c_operator_0_zero_diffuzer_0_zero_diffuzer_aux_control_name q3,q5,q6,q7,q8;
  c_operator_0_zero_diffuzer_0_mcx_0 q0,q1,q2,q3,q9;
}

gate mcx_hybrid_gray_code_maslov15_140138896474832 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140138896474832_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140138896474832 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_0_statepreparation_0_rygate_2_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140138896474832_o0 q0,q1,q2;
}

gate c_operator_0_statepreparation_0_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_0_rygate_2_mcx_0 q1,q2,q0;
  ry(-pi/4) q0;
  c_operator_0_statepreparation_0_rygate_2_mcx_0 q1,q2,q0;
  ry(pi/4) q0;
}

gate mcx_hybrid_gray_code_maslov15 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_0_rygate_1_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_o0 q0,q1;
}

gate c_operator_0_statepreparation_0_rygate_1 q0,q1 {
  c_operator_0_statepreparation_0_rygate_1_mcx_0 q1,q0;
  ry(-0.1699184547270609) q0;
  c_operator_0_statepreparation_0_rygate_1_mcx_0 q1,q0;
  ry(0.1699184547270609) q0;
}

gate c_operator_0_statepreparation_0 q0,q1,q2 {
  h q0;
  h q1;
  h q2;
  ry(0.14334756890536537) q2;
  c_operator_0_statepreparation_0_rygate_1 q1,q2;
  c_operator_0_statepreparation_0_rygate_2 q0,q1,q2;
}

gate c_operator_0_inplace_prepare_int_0 q0,q1,q2 {
  x q0;
  x q1;
  x q2;
}

gate apply_to_all_expanded___3 q0,q1,q2 {
  h q0;
  h q1;
  h q2;
}

gate main_hadamard_transform q0,q1,q2 {
  apply_to_all_expanded___3 q0,q1,q2;
}

gate main_c_operator_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24 {
  c_operator_0_inplace_prepare_int_0 q0,q1,q2;
  c_operator_0_statepreparation_0 q5,q6,q7;
  c_operator_0_zero_diffuzer_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
  c_operator_0_statepreparation_1 q5,q6,q7;
  c_operator_0_statepreparation_2 q5,q6,q7;
  c_operator_0_inplace_prepare_int_1 q0,q1,q2;
  c_operator_0_inplace_prepare_int_2 q0,q1,q2;
  c_operator_0_zero_diffuzer_1 q0,q1,q2,q5,q6,q7,q10,q11,q12,q13;
  c_operator_0_statepreparation_3 q5,q6,q7;
  c_operator_0_statepreparation_4 q5,q6,q7;
  c_operator_0_inplace_prepare_int_3 q0,q1,q2;
  c_operator_0_inplace_prepare_int_4 q0,q1,q2;
  c_operator_0_zero_diffuzer_2 q0,q1,q2,q5,q6,q7,q14,q15,q16,q17;
  c_operator_0_statepreparation_5 q5,q6,q7;
  c_operator_0_statepreparation_6 q5,q6,q7;
  c_operator_0_inplace_prepare_int_5 q0,q1,q2;
  c_operator_0_inplace_prepare_int_6 q0,q1,q2;
  c_operator_0_zero_diffuzer_3 q0,q1,q2,q5,q6,q7,q18,q19,q20,q21;
  c_operator_0_statepreparation_7 q5,q6,q7;
  c_operator_0_statepreparation_8 q5,q6,q7;
  c_operator_0_inplace_prepare_int_7 q0,q1,q2;
  c_operator_0_inplace_prepare_int_8 q0,q1,q2;
  c_operator_0_zero_diffuzer_4 q0,q1,q2,q5,q6,q7,q18,q22,q23,q24;
  c_operator_0_statepreparation_9 q5,q6,q7;
  c_operator_0_statepreparation_10 q5,q6,q7;
  c_operator_0_inplace_prepare_int_9 q0,q1,q2;
  c_operator_0_inplace_prepare_int_10 q0,q1,q2;
  c_operator_0_zero_diffuzer_5 q0,q1,q2,q3,q5,q6,q7,q9,q14,q21;
  c_operator_0_statepreparation_11 q5,q6,q7;
  c_operator_0_statepreparation_12 q5,q6,q7;
  c_operator_0_inplace_prepare_int_11 q0,q1,q2;
  c_operator_0_inplace_prepare_int_12 q0,q1,q2;
  c_operator_0_zero_diffuzer_6 q0,q1,q2,q3,q5,q6,q7,q17,q19,q22;
  c_operator_0_statepreparation_13 q5,q6,q7;
  c_operator_0_statepreparation_14 q5,q6,q7;
  c_operator_0_inplace_prepare_int_13 q0,q1,q2;
  c_operator_0_zero_diffuzer_7 q0,q1,q2,q3,q5,q6,q7,q9,q10;
  c_operator_0_statepreparation_15 q5,q6,q7;
}

gate main_s_operator_0 q0,q1,q2,q3,q4,q5,q6 {
  s_operator_0_edge_oracle q0,q1,q2,q3,q4,q5,q6;
  s_operator_0_bitwise_swap q6,q0,q1,q2,q3,q4,q5;
}

gate main_c_operator_1 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15 {
  c_operator_1_statepreparation_0 q5,q6,q7;
  c_operator_1_inplace_prepare_int_0 q0,q1,q2;
  c_operator_1_zero_diffuzer_0 q0,q1,q2,q5,q6,q7,q10,q13,q15;
  c_operator_1_statepreparation_1 q5,q6,q7;
  c_operator_1_statepreparation_2 q5,q6,q7;
  c_operator_1_inplace_prepare_int_1 q0,q1,q2;
  c_operator_1_inplace_prepare_int_2 q0,q1,q2;
  c_operator_1_zero_diffuzer_1 q0,q1,q2,q3,q5,q6,q7,q10,q13;
  c_operator_1_statepreparation_3 q5,q6,q7;
  c_operator_1_statepreparation_4 q5,q6,q7;
  c_operator_1_inplace_prepare_int_3 q0,q1,q2;
  c_operator_1_inplace_prepare_int_4 q0,q1,q2;
  c_operator_1_zero_diffuzer_2 q0,q1,q2,q4,q5,q6,q7,q10,q12,q13;
  c_operator_1_statepreparation_5 q5,q6,q7;
  c_operator_1_statepreparation_6 q5,q6,q7;
  c_operator_1_inplace_prepare_int_5 q0,q1,q2;
  c_operator_1_inplace_prepare_int_6 q0,q1,q2;
  c_operator_1_zero_diffuzer_3 q0,q1,q2,q5,q6,q7,q9,q10,q11,q14;
  c_operator_1_statepreparation_7 q5,q6,q7;
  c_operator_1_statepreparation_8 q5,q6,q7;
  c_operator_1_inplace_prepare_int_7 q0,q1,q2;
  c_operator_1_inplace_prepare_int_8 q0,q1,q2;
  c_operator_1_zero_diffuzer_4 q0,q1,q2,q5,q6,q7,q8,q11,q12,q13;
  c_operator_1_statepreparation_9 q5,q6,q7;
  c_operator_1_statepreparation_10 q5,q6,q7;
  c_operator_1_inplace_prepare_int_9 q0,q1,q2;
  c_operator_1_inplace_prepare_int_10 q0,q1,q2;
  c_operator_1_zero_diffuzer_5 q0,q1,q2,q5,q6,q7,q8,q10,q11,q13;
  c_operator_1_statepreparation_11 q5,q6,q7;
  c_operator_1_statepreparation_12 q5,q6,q7;
  c_operator_1_inplace_prepare_int_11 q0,q1,q2;
  c_operator_1_inplace_prepare_int_12 q0,q1,q2;
  c_operator_1_zero_diffuzer_6 q0,q1,q2,q5,q6,q7,q8,q11,q13,q14;
  c_operator_1_statepreparation_13 q5,q6,q7;
  c_operator_1_statepreparation_14 q5,q6,q7;
  c_operator_1_inplace_prepare_int_13 q0,q1,q2;
  c_operator_1_zero_diffuzer_7 q0,q1,q2,q5,q6,q7,q8,q11,q13;
  c_operator_1_statepreparation_15 q5,q6,q7;
}

gate main_s_operator_1 q0,q1,q2,q3,q4,q5,q6 {
  s_operator_1_edge_oracle q0,q1,q2,q3,q4,q5,q6;
  s_operator_1_bitwise_swap q6,q0,q1,q2,q3,q4,q5;
}

qreg q[25];
main_hadamard_transform q[0],q[1],q[2];
main_c_operator_0 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24];
main_s_operator_0 q[0],q[1],q[2],q[5],q[6],q[7],q[9];
main_c_operator_1 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[11],q[13],q[15],q[17],q[18],q[21],q[22],q[23];
main_s_operator_1 q[0],q[1],q[2],q[5],q[6],q[7],q[11];
