// Generated by Classiq.
// Classiq version: 0.46.0
// Creation timestamp: 2024-08-24T03:00:52.601399+00:00
// Random seed: 533371823

OPENQASM 2.0;
include "qelib1.inc";
gate cbitwise_swap_expanded___156 q0,q1,q2,q3,q4,q5,q6 {
  cswap q0,q1,q4;
  cswap q0,q2,q5;
  cswap q0,q3,q6;
}

gate s_operator_2_bitwise_swap q0,q1,q2,q3,q4,q5,q6 {
  cbitwise_swap_expanded___156 q0,q1,q2,q3,q4,q5,q6;
}

gate s_operator_2_edge_oracle_arithmetic_adder_1 q0,q1,q2,q3,q4,q5 {
  cx q3,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387446032656 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387446040080 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387446032656 q0,q1;
}

gate s_operator_2_edge_oracle_arithmetic_equal q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387446040080 q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_adder_0_140387453776144 q0,q1,q2,q3,q4,q5 {
  cx q3,q0;
}

gate s_operator_2_edge_oracle_arithmetic q0,q1,q2,q3,q4,q5,q6 {
  s_operator_0_edge_oracle_arithmetic_adder_0_140387453776144 q0,q1,q2,q3,q4,q5;
  s_operator_2_edge_oracle_arithmetic_equal q0,q6;
  s_operator_2_edge_oracle_arithmetic_adder_1 q0,q1,q2,q3,q4,q5;
}

gate s_operator_2_edge_oracle q0,q1,q2,q3,q4,q5,q6 {
  s_operator_2_edge_oracle_arithmetic q0,q1,q2,q3,q4,q5,q6;
}

gate c_operator_2_statepreparation_15_computationalbasisstatepreparation_qinverse q0,q1,q2 {
  x q2;
  x q1;
}

gate c_operator_2_statepreparation_15 q0,q1,q2 {
  c_operator_2_statepreparation_15_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_2_zero_diffuzer_7_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387446038160 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387288406608 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387446038160 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387446038160 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387288400080 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387288406608 q0,q1,q2,q3,q4;
}

gate c_operator_2_zero_diffuzer_7 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387288400080 q0,q1,q2,q4,q5;
  c_operator_2_zero_diffuzer_7_zero_diffuzer_aux_control_name q3,q4,q6,q7,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387288400080 q0,q1,q2,q4,q9;
}

gate c_operator_2_inplace_prepare_int_13 q0,q1,q2 {
  x q0;
}

gate c_operator_0_statepreparation_14_computationalbasisstatepreparation_140387452543760 q0,q1,q2 {
  x q1;
  x q2;
}

gate c_operator_2_statepreparation_14 q0,q1,q2 {
  c_operator_0_statepreparation_14_computationalbasisstatepreparation_140387452543760 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387452550544 q0,q1 {
  cx q0,q1;
}

gate c_operator_2_statepreparation_13_rygate_2_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387452550544 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387454744720 q0,q1 {
  cx q0,q1;
}

gate c_operator_2_statepreparation_13_rygate_2_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387454744720 q0,q1;
}

gate c_operator_2_statepreparation_13_rygate_2_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_2_statepreparation_13_rygate_2_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_2_statepreparation_13_rygate_2_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387454733328 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387454733328_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387454733328 q0,q1,q2;
  x q0;
}

gate c_operator_2_statepreparation_13_rygate_1_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387454733328_o2 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387454731984 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387454731984_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387454731984 q0,q1,q2;
  x q0;
}

gate c_operator_2_statepreparation_13_rygate_1_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387454731984_o2 q0,q1,q2;
}

gate c_operator_2_statepreparation_13_rygate_1_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_2_statepreparation_13_rygate_1_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_2_statepreparation_13_rygate_1_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate mcx_hybrid_gray_code_maslov15_140388142358032 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate c_operator_2_statepreparation_13_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140388142358032 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140391068030992 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate c_operator_2_statepreparation_13_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140391068030992 q0,q1,q2;
}

gate c_operator_2_statepreparation_13_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_2_statepreparation_13_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_2_statepreparation_13_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_2_statepreparation_13 q0,q1,q2 {
  c_operator_2_statepreparation_13_rygate_0_qinverse q0,q1,q2;
  c_operator_2_statepreparation_13_rygate_1_qinverse q0,q1,q2;
  c_operator_2_statepreparation_13_rygate_2_qinverse q1,q2;
  ry(-pi) q2;
}

gate c_operator_2_zero_diffuzer_6_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387456429648 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387621642064 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387456429648 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387456429648 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387621647952 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387621642064 q0,q1,q2,q3,q4;
}

gate c_operator_2_zero_diffuzer_6 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387621647952 q0,q1,q2,q3,q4;
  c_operator_2_zero_diffuzer_6_zero_diffuzer_aux_control_name q3,q5,q6,q7,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387621647952 q0,q1,q2,q3,q9;
}

gate c_operator_2_inplace_prepare_int_12 q0,q1,q2 {
  x q0;
}

gate c_operator_2_inplace_prepare_int_11 q0,q1,q2 {
  x q1;
}

gate mcx_hybrid_gray_code_maslov15_140387456505168 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate c_operator_0_statepreparation_12_rygate_3_mcx_0_140387456506960 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387456505168 q0,q1,q2;
}

gate c_operator_2_statepreparation_12_rygate_3 q0,q1,q2 {
  c_operator_0_statepreparation_12_rygate_3_mcx_0_140387456506960 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_12_rygate_3_mcx_0_140387456506960 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387455748112 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387455748112_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387455748112 q0,q1,q2;
  x q0;
}

gate c_operator_0_statepreparation_8_rygate_4_mcx_0_140387135898896 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387455748112_o2 q0,q1,q2;
}

gate c_operator_2_statepreparation_12_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_8_rygate_4_mcx_0_140387135898896 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_8_rygate_4_mcx_0_140387135898896 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387708222736 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387708221072 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387708222736 q0,q1;
}

gate c_operator_2_statepreparation_12_rygate_1 q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387708221072 q1,q0;
  ry(-pi/4) q0;
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387708221072 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_2_statepreparation_12 q0,q1,q2 {
  ry(pi) q2;
  c_operator_2_statepreparation_12_rygate_1 q1,q2;
  c_operator_2_statepreparation_12_rygate_2 q0,q1,q2;
  c_operator_2_statepreparation_12_rygate_3 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388603457872 q0,q1 {
  cx q0,q1;
}

gate c_operator_2_statepreparation_11_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388603457872 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140388603450960 q0,q1 {
  cx q0,q1;
}

gate c_operator_2_statepreparation_11_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388603450960 q0,q1;
}

gate c_operator_2_statepreparation_11_rygate_0_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_2_statepreparation_11_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_2_statepreparation_11_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate c_operator_2_statepreparation_11 q0,q1,q2 {
  c_operator_2_statepreparation_11_rygate_0_qinverse q1,q2;
  ry(-pi) q2;
}

gate c_operator_2_zero_diffuzer_5_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387447030672 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387455749264 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387447030672 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387447030672 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387455757520 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387455749264 q0,q1,q2,q3,q4;
}

gate c_operator_2_zero_diffuzer_5 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387455757520 q0,q1,q2,q6,q7;
  c_operator_2_zero_diffuzer_5_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387455757520 q0,q1,q2,q6,q9;
}

gate c_operator_2_inplace_prepare_int_10 q0,q1,q2 {
  x q1;
}

gate c_operator_2_inplace_prepare_int_9 q0,q1,q2 {
  x q1;
  x q0;
}

gate mcx_hybrid_gray_code_maslov15_140387456846544 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387456845328 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387456846544 q0,q1;
}

gate c_operator_2_statepreparation_10_rygate_1 q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387456845328 q1,q0;
  ry(-pi/4) q0;
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387456845328 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_2_statepreparation_10 q0,q1,q2 {
  ry(pi) q2;
  c_operator_2_statepreparation_10_rygate_1 q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387452924560 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387452924560_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387452924560 q0,q1;
  x q0;
}

gate c_operator_2_statepreparation_9_rygate_3_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387452924560_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387452921168 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387452921168_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387452921168 q0,q1;
  x q0;
}

gate c_operator_2_statepreparation_9_rygate_3_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387452921168_o0 q0,q1;
}

gate c_operator_2_statepreparation_9_rygate_3_qinverse q0,q1 {
  ry(-pi/2) q0;
  c_operator_2_statepreparation_9_rygate_3_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/2) q0;
  c_operator_2_statepreparation_9_rygate_3_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387452921296 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387452921296_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387452921296 q0,q1,q2;
  x q1;
}

gate c_operator_2_statepreparation_9_rygate_2_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387452921296_o1 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387474196944 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387474196944_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387474196944 q0,q1,q2;
  x q1;
}

gate c_operator_2_statepreparation_9_rygate_2_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387474196944_o1 q0,q1,q2;
}

gate c_operator_2_statepreparation_9_rygate_2_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_2_statepreparation_9_rygate_2_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_2_statepreparation_9_rygate_2_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387474210384 q0,q1 {
  cx q0,q1;
}

gate c_operator_2_statepreparation_9_rygate_1_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387474210384 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140388973640016 q0,q1 {
  cx q0,q1;
}

gate c_operator_2_statepreparation_9_rygate_1_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388973640016 q0,q1;
}

gate c_operator_2_statepreparation_9_rygate_1_qinverse q0,q1 {
  c_operator_2_statepreparation_9_rygate_1_qinverse_mcx_0_qinverse q1,q0;
  c_operator_2_statepreparation_9_rygate_1_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140388973637904 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388973637904_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140388973637904 q0,q1,q2;
  x q0;
}

gate c_operator_2_statepreparation_9_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140388973637904_o2 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388973634640 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388973634640_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140388973634640 q0,q1,q2;
  x q0;
}

gate c_operator_2_statepreparation_9_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140388973634640_o2 q0,q1,q2;
}

gate c_operator_2_statepreparation_9_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_2_statepreparation_9_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_2_statepreparation_9_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_2_statepreparation_9 q0,q1,q2 {
  c_operator_2_statepreparation_9_rygate_0_qinverse q0,q1,q2;
  c_operator_2_statepreparation_9_rygate_1_qinverse q1,q2;
  c_operator_2_statepreparation_9_rygate_2_qinverse q0,q1,q2;
  c_operator_2_statepreparation_9_rygate_3_qinverse q1,q2;
  ry(-pi/2) q2;
}

gate c_operator_2_zero_diffuzer_4_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140388151199760 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387474207632 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140388151199760 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140388151199760 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387474205968 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387474207632 q0,q1,q2,q3,q4;
}

gate c_operator_2_zero_diffuzer_4 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387474205968 q0,q1,q2,q6,q7;
  c_operator_2_zero_diffuzer_4_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387474205968 q0,q1,q2,q6,q9;
}

gate c_operator_2_inplace_prepare_int_8 q0,q1,q2 {
  x q0;
  x q1;
}

gate c_operator_2_inplace_prepare_int_7 q0,q1,q2 {
  x q2;
}

gate mcx_hybrid_gray_code_maslov15_140387457396432 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387457396432_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387457396432 q0,q1,q2;
  x q0;
}

gate c_operator_0_statepreparation_8_rygate_4_mcx_0_140387457398864 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387457396432_o2 q0,q1,q2;
}

gate c_operator_2_statepreparation_8_rygate_4 q0,q1,q2 {
  c_operator_0_statepreparation_8_rygate_4_mcx_0_140387457398864 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_8_rygate_4_mcx_0_140387457398864 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387448915472 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387448928656 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387448915472 q0,q1;
}

gate c_operator_2_statepreparation_8_rygate_3 q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387448928656 q1,q0;
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387448928656 q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387448927760 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387448927760_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387448927760 q0,q1,q2;
  x q1;
}

gate c_operator_0_statepreparation_4_rygate_3_mcx_0_140387448918480 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387448927760_o1 q0,q1,q2;
}

gate c_operator_2_statepreparation_8_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_4_rygate_3_mcx_0_140387448918480 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_4_rygate_3_mcx_0_140387448918480 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387448920400 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387448920400_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387448920400 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140387448929744 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387448920400_o0 q0,q1;
}

gate c_operator_2_statepreparation_8_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387448929744 q1,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387448929744 q1,q0;
  ry(pi/2) q0;
}

gate c_operator_2_statepreparation_8 q0,q1,q2 {
  ry(pi/2) q2;
  c_operator_2_statepreparation_8_rygate_1 q1,q2;
  c_operator_2_statepreparation_8_rygate_2 q0,q1,q2;
  c_operator_2_statepreparation_8_rygate_3 q1,q2;
  c_operator_2_statepreparation_8_rygate_4 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387325515408 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387325515408_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387325515408 q0,q1;
  x q0;
}

gate c_operator_2_statepreparation_7_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387325515408_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387401157904 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387401157904_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387401157904 q0,q1;
  x q0;
}

gate c_operator_2_statepreparation_7_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387401157904_o0 q0,q1;
}

gate c_operator_2_statepreparation_7_rygate_0_qinverse q0,q1 {
  ry(-pi/2) q0;
  c_operator_2_statepreparation_7_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/2) q0;
  c_operator_2_statepreparation_7_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate c_operator_2_statepreparation_7 q0,q1,q2 {
  c_operator_2_statepreparation_7_rygate_0_qinverse q1,q2;
  ry(-pi/2) q2;
}

gate c_operator_2_zero_diffuzer_3_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387449382416 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387401167824 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387449382416 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387449382416 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387401164752 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387401167824 q0,q1,q2,q3,q4;
}

gate c_operator_2_zero_diffuzer_3 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387401164752 q0,q1,q2,q6,q7;
  c_operator_2_zero_diffuzer_3_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387401164752 q0,q1,q2,q6,q9;
}

gate c_operator_2_inplace_prepare_int_6 q0,q1,q2 {
  x q2;
}

gate c_operator_2_inplace_prepare_int_5 q0,q1,q2 {
  x q2;
  x q0;
}

gate mcx_hybrid_gray_code_maslov15_140387325512848 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387325512848_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387325512848 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140387325514832 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387325512848_o0 q0,q1;
}

gate c_operator_2_statepreparation_6_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387325514832 q1,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387325514832 q1,q0;
  ry(pi/2) q0;
}

gate c_operator_2_statepreparation_6 q0,q1,q2 {
  ry(pi/2) q2;
  c_operator_2_statepreparation_6_rygate_1 q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387284480656 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387284480656_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387284480656 q0,q1;
  x q0;
}

gate c_operator_2_statepreparation_5_rygate_2_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387284480656_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387332152400 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387332152400_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387332152400 q0,q1;
  x q0;
}

gate c_operator_2_statepreparation_5_rygate_2_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387332152400_o0 q0,q1;
}

gate c_operator_2_statepreparation_5_rygate_2_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_2_statepreparation_5_rygate_2_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_2_statepreparation_5_rygate_2_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387332160272 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387332160272_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140387332160272 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_2_statepreparation_5_rygate_1_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387332160272_o0 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387332156432 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387332156432_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140387332156432 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_2_statepreparation_5_rygate_1_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387332156432_o0 q0,q1,q2;
}

gate c_operator_2_statepreparation_5_rygate_1_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_2_statepreparation_5_rygate_1_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_2_statepreparation_5_rygate_1_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387332158480 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387332158480_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387332158480 q0,q1,q2;
  x q1;
}

gate c_operator_2_statepreparation_5_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387332158480_o1 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387332154256 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387332154256_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387332154256 q0,q1,q2;
  x q1;
}

gate c_operator_2_statepreparation_5_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387332154256_o1 q0,q1,q2;
}

gate c_operator_2_statepreparation_5_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_2_statepreparation_5_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_2_statepreparation_5_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_2_statepreparation_5 q0,q1,q2 {
  c_operator_2_statepreparation_5_rygate_0_qinverse q0,q1,q2;
  c_operator_2_statepreparation_5_rygate_1_qinverse q0,q1,q2;
  c_operator_2_statepreparation_5_rygate_2_qinverse q1,q2;
  ry(0) q2;
}

gate c_operator_2_zero_diffuzer_2_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387401160976 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387167120464 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387401160976 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387401160976 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387167123344 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387167120464 q0,q1,q2,q3,q4;
}

gate c_operator_2_zero_diffuzer_2 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387167123344 q0,q1,q2,q6,q7;
  c_operator_2_zero_diffuzer_2_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387167123344 q0,q1,q2,q6,q9;
}

gate c_operator_2_inplace_prepare_int_4 q0,q1,q2 {
  x q0;
  x q2;
}

gate c_operator_2_inplace_prepare_int_3 q0,q1,q2 {
  x q2;
  x q1;
}

gate mcx_hybrid_gray_code_maslov15_140387284482320 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387284482320_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387284482320 q0,q1,q2;
  x q1;
}

gate c_operator_0_statepreparation_4_rygate_3_mcx_0_140387284471632 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387284482320_o1 q0,q1,q2;
}

gate c_operator_2_statepreparation_4_rygate_3 q0,q1,q2 {
  c_operator_0_statepreparation_4_rygate_3_mcx_0_140387284471632 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_4_rygate_3_mcx_0_140387284471632 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387814323344 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387814323344_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140387814323344 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_0_statepreparation_4_rygate_2_mcx_0_140387814319504 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387814323344_o0 q0,q1,q2;
}

gate c_operator_2_statepreparation_4_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_4_rygate_2_mcx_0_140387814319504 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_4_rygate_2_mcx_0_140387814319504 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387284140816 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387284140816_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387284140816 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140387284155728 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387284140816_o0 q0,q1;
}

gate c_operator_2_statepreparation_4_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387284155728 q1,q0;
  ry(-pi/4) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387284155728 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_2_statepreparation_4 q0,q1,q2 {
  ry(0) q2;
  c_operator_2_statepreparation_4_rygate_1 q1,q2;
  c_operator_2_statepreparation_4_rygate_2 q0,q1,q2;
  c_operator_2_statepreparation_4_rygate_3 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387284145488 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387284145488_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387284145488 q0,q1;
  x q0;
}

gate c_operator_2_statepreparation_3_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387284145488_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387284149328 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387284149328_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387284149328 q0,q1;
  x q0;
}

gate c_operator_2_statepreparation_3_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387284149328_o0 q0,q1;
}

gate c_operator_2_statepreparation_3_rygate_0_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_2_statepreparation_3_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_2_statepreparation_3_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate c_operator_2_statepreparation_3 q0,q1,q2 {
  c_operator_2_statepreparation_3_rygate_0_qinverse q1,q2;
  ry(0) q2;
}

gate c_operator_2_zero_diffuzer_1_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387360815184 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387284143248 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387360815184 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387360815184 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387284147024 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387284143248 q0,q1,q2,q3,q4;
}

gate c_operator_2_zero_diffuzer_1 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387284147024 q0,q1,q2,q6,q7;
  c_operator_2_zero_diffuzer_1_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387284147024 q0,q1,q2,q6,q9;
}

gate c_operator_2_inplace_prepare_int_2 q0,q1,q2 {
  x q1;
  x q2;
}

gate c_operator_2_inplace_prepare_int_1 q0,q1,q2 {
  x q2;
  x q1;
  x q0;
}

gate mcx_hybrid_gray_code_maslov15_140387264612048 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387264612048_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387264612048 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140387264611984 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387264612048_o0 q0,q1;
}

gate c_operator_2_statepreparation_2_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387264611984 q1,q0;
  ry(-pi/4) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387264611984 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_2_statepreparation_2 q0,q1,q2 {
  ry(0) q2;
  c_operator_2_statepreparation_2_rygate_1 q1,q2;
}

gate c_operator_2_statepreparation_1_computationalbasisstatepreparation_qinverse q0,q1,q2 {
  x q0;
}

gate c_operator_2_statepreparation_1 q0,q1,q2 {
  c_operator_2_statepreparation_1_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_2_zero_diffuzer_0_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387284523536 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387358882832 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387284523536 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387284523536 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140388299716176 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387358882832 q0,q1,q2,q3,q4;
}

gate c_operator_2_zero_diffuzer_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140388299716176 q0,q1,q2,q6,q7;
  c_operator_2_zero_diffuzer_0_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140388299716176 q0,q1,q2,q6,q9;
}

gate c_operator_2_inplace_prepare_int_0 q0,q1,q2 {
  x q0;
  x q1;
  x q2;
}

gate c_operator_0_statepreparation_0_computationalbasisstatepreparation_140387248038864 q0,q1,q2 {
  x q0;
}

gate c_operator_2_statepreparation_0 q0,q1,q2 {
  c_operator_0_statepreparation_0_computationalbasisstatepreparation_140387248038864 q0,q1,q2;
}

gate cbitwise_swap_expanded___105 q0,q1,q2,q3,q4,q5,q6 {
  cswap q0,q1,q4;
  cswap q0,q2,q5;
  cswap q0,q3,q6;
}

gate s_operator_1_bitwise_swap q0,q1,q2,q3,q4,q5,q6 {
  cbitwise_swap_expanded___105 q0,q1,q2,q3,q4,q5,q6;
}

gate s_operator_1_edge_oracle_arithmetic_adder_1 q0,q1,q2,q3,q4,q5 {
  cx q3,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387185645456 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387185648080 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387185645456 q0,q1;
}

gate s_operator_1_edge_oracle_arithmetic_equal q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387185648080 q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_adder_0_140387185654160 q0,q1,q2,q3,q4,q5 {
  cx q3,q0;
}

gate s_operator_1_edge_oracle_arithmetic q0,q1,q2,q3,q4,q5,q6 {
  s_operator_0_edge_oracle_arithmetic_adder_0_140387185654160 q0,q1,q2,q3,q4,q5;
  s_operator_1_edge_oracle_arithmetic_equal q0,q6;
  s_operator_1_edge_oracle_arithmetic_adder_1 q0,q1,q2,q3,q4,q5;
}

gate s_operator_1_edge_oracle q0,q1,q2,q3,q4,q5,q6 {
  s_operator_1_edge_oracle_arithmetic q0,q1,q2,q3,q4,q5,q6;
}

gate c_operator_1_statepreparation_15_computationalbasisstatepreparation_qinverse q0,q1,q2 {
  x q2;
  x q1;
}

gate c_operator_1_statepreparation_15 q0,q1,q2 {
  c_operator_1_statepreparation_15_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_1_zero_diffuzer_7_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387185646416 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387461204944 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387185646416 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387185646416 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387461210512 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387461204944 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_7 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387461210512 q0,q1,q2,q3,q4;
  c_operator_1_zero_diffuzer_7_zero_diffuzer_aux_control_name q5,q3,q6,q7,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387461210512 q0,q1,q2,q3,q9;
}

gate c_operator_1_inplace_prepare_int_13 q0,q1,q2 {
  x q0;
}

gate c_operator_0_statepreparation_14_computationalbasisstatepreparation_140387717244432 q0,q1,q2 {
  x q1;
  x q2;
}

gate c_operator_1_statepreparation_14 q0,q1,q2 {
  c_operator_0_statepreparation_14_computationalbasisstatepreparation_140387717244432 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388288708112 q0,q1 {
  cx q0,q1;
}

gate c_operator_1_statepreparation_13_rygate_2_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388288708112 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140388309779920 q0,q1 {
  cx q0,q1;
}

gate c_operator_1_statepreparation_13_rygate_2_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388309779920 q0,q1;
}

gate c_operator_1_statepreparation_13_rygate_2_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_1_statepreparation_13_rygate_2_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_1_statepreparation_13_rygate_2_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140388309791888 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388309791888_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140388309791888 q0,q1,q2;
  x q0;
}

gate c_operator_1_statepreparation_13_rygate_1_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140388309791888_o2 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388309781584 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388309781584_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140388309781584 q0,q1,q2;
  x q0;
}

gate c_operator_1_statepreparation_13_rygate_1_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140388309781584_o2 q0,q1,q2;
}

gate c_operator_1_statepreparation_13_rygate_1_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_1_statepreparation_13_rygate_1_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_1_statepreparation_13_rygate_1_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387699930512 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate c_operator_1_statepreparation_13_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387699930512 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387398117840 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate c_operator_1_statepreparation_13_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387398117840 q0,q1,q2;
}

gate c_operator_1_statepreparation_13_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_1_statepreparation_13_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_1_statepreparation_13_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_1_statepreparation_13 q0,q1,q2 {
  c_operator_1_statepreparation_13_rygate_0_qinverse q0,q1,q2;
  c_operator_1_statepreparation_13_rygate_1_qinverse q0,q1,q2;
  c_operator_1_statepreparation_13_rygate_2_qinverse q1,q2;
  ry(-pi) q2;
}

gate c_operator_1_zero_diffuzer_6_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140388082767504 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387185913360 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140388082767504 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140388082767504 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387185917776 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387185913360 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_6 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387185917776 q0,q1,q2,q9,q3;
  c_operator_1_zero_diffuzer_6_zero_diffuzer_aux_control_name q4,q5,q6,q7,q9;
  c_operator_0_zero_diffuzer_0_mcx_0_140387185917776 q0,q1,q2,q9,q8;
}

gate c_operator_1_inplace_prepare_int_12 q0,q1,q2 {
  x q0;
}

gate c_operator_1_inplace_prepare_int_11 q0,q1,q2 {
  x q1;
}

gate mcx_hybrid_gray_code_maslov15_140387285129296 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate c_operator_0_statepreparation_12_rygate_3_mcx_0_140387285138384 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387285129296 q0,q1,q2;
}

gate c_operator_1_statepreparation_12_rygate_3 q0,q1,q2 {
  c_operator_0_statepreparation_12_rygate_3_mcx_0_140387285138384 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_12_rygate_3_mcx_0_140387285138384 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387398120976 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387398120976_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387398120976 q0,q1,q2;
  x q0;
}

gate c_operator_0_statepreparation_8_rygate_4_mcx_0_140387398117392 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387398120976_o2 q0,q1,q2;
}

gate c_operator_1_statepreparation_12_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_8_rygate_4_mcx_0_140387398117392 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_8_rygate_4_mcx_0_140387398117392 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387475613904 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387475614416 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387475613904 q0,q1;
}

gate c_operator_1_statepreparation_12_rygate_1 q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387475614416 q1,q0;
  ry(-pi/4) q0;
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387475614416 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_1_statepreparation_12 q0,q1,q2 {
  ry(pi) q2;
  c_operator_1_statepreparation_12_rygate_1 q1,q2;
  c_operator_1_statepreparation_12_rygate_2 q0,q1,q2;
  c_operator_1_statepreparation_12_rygate_3 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387711489808 q0,q1 {
  cx q0,q1;
}

gate c_operator_1_statepreparation_11_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387711489808 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387711496272 q0,q1 {
  cx q0,q1;
}

gate c_operator_1_statepreparation_11_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387711496272 q0,q1;
}

gate c_operator_1_statepreparation_11_rygate_0_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_1_statepreparation_11_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_1_statepreparation_11_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate c_operator_1_statepreparation_11 q0,q1,q2 {
  c_operator_1_statepreparation_11_rygate_0_qinverse q1,q2;
  ry(-pi) q2;
}

gate c_operator_1_zero_diffuzer_5_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387394889488 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140388346970768 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387394889488 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387394889488 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387852810000 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140388346970768 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_5 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387852810000 q0,q1,q2,q6,q7;
  c_operator_1_zero_diffuzer_5_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387852810000 q0,q1,q2,q6,q9;
}

gate c_operator_1_inplace_prepare_int_10 q0,q1,q2 {
  x q1;
}

gate c_operator_1_inplace_prepare_int_9 q0,q1,q2 {
  x q1;
  x q0;
}

gate mcx_hybrid_gray_code_maslov15_140387374948752 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387374946192 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387374948752 q0,q1;
}

gate c_operator_1_statepreparation_10_rygate_1 q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387374946192 q1,q0;
  ry(-pi/4) q0;
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387374946192 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_1_statepreparation_10 q0,q1,q2 {
  ry(pi) q2;
  c_operator_1_statepreparation_10_rygate_1 q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387346979664 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387346979664_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387346979664 q0,q1;
  x q0;
}

gate c_operator_1_statepreparation_9_rygate_3_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387346979664_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387346988624 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387346988624_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387346988624 q0,q1;
  x q0;
}

gate c_operator_1_statepreparation_9_rygate_3_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387346988624_o0 q0,q1;
}

gate c_operator_1_statepreparation_9_rygate_3_qinverse q0,q1 {
  ry(-pi/2) q0;
  c_operator_1_statepreparation_9_rygate_3_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/2) q0;
  c_operator_1_statepreparation_9_rygate_3_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387139684432 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387139684432_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387139684432 q0,q1,q2;
  x q1;
}

gate c_operator_1_statepreparation_9_rygate_2_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387139684432_o1 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387588045456 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387588045456_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387588045456 q0,q1,q2;
  x q1;
}

gate c_operator_1_statepreparation_9_rygate_2_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387588045456_o1 q0,q1,q2;
}

gate c_operator_1_statepreparation_9_rygate_2_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_1_statepreparation_9_rygate_2_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_1_statepreparation_9_rygate_2_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387588043728 q0,q1 {
  cx q0,q1;
}

gate c_operator_1_statepreparation_9_rygate_1_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387588043728 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387588031824 q0,q1 {
  cx q0,q1;
}

gate c_operator_1_statepreparation_9_rygate_1_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387588031824 q0,q1;
}

gate c_operator_1_statepreparation_9_rygate_1_qinverse q0,q1 {
  c_operator_1_statepreparation_9_rygate_1_qinverse_mcx_0_qinverse q1,q0;
  c_operator_1_statepreparation_9_rygate_1_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387588034704 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387588034704_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387588034704 q0,q1,q2;
  x q0;
}

gate c_operator_1_statepreparation_9_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387588034704_o2 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140389099655824 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140389099655824_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140389099655824 q0,q1,q2;
  x q0;
}

gate c_operator_1_statepreparation_9_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140389099655824_o2 q0,q1,q2;
}

gate c_operator_1_statepreparation_9_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_1_statepreparation_9_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_1_statepreparation_9_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_1_statepreparation_9 q0,q1,q2 {
  c_operator_1_statepreparation_9_rygate_0_qinverse q0,q1,q2;
  c_operator_1_statepreparation_9_rygate_1_qinverse q1,q2;
  c_operator_1_statepreparation_9_rygate_2_qinverse q0,q1,q2;
  c_operator_1_statepreparation_9_rygate_3_qinverse q1,q2;
  ry(-pi/2) q2;
}

gate c_operator_1_zero_diffuzer_4_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387985219792 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387346984464 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387985219792 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387985219792 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387346973904 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387346984464 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_4 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387346973904 q0,q1,q2,q6,q7;
  c_operator_1_zero_diffuzer_4_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387346973904 q0,q1,q2,q6,q9;
}

gate c_operator_1_inplace_prepare_int_8 q0,q1,q2 {
  x q0;
  x q1;
}

gate c_operator_1_inplace_prepare_int_7 q0,q1,q2 {
  x q2;
}

gate mcx_hybrid_gray_code_maslov15_140387299262544 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387299262544_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387299262544 q0,q1,q2;
  x q0;
}

gate c_operator_0_statepreparation_8_rygate_4_mcx_0_140387299278672 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387299262544_o2 q0,q1,q2;
}

gate c_operator_1_statepreparation_8_rygate_4 q0,q1,q2 {
  c_operator_0_statepreparation_8_rygate_4_mcx_0_140387299278672 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_8_rygate_4_mcx_0_140387299278672 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387299273040 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387299277712 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387299273040 q0,q1;
}

gate c_operator_1_statepreparation_8_rygate_3 q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387299277712 q1,q0;
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387299277712 q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387288364496 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387288364496_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387288364496 q0,q1,q2;
  x q1;
}

gate c_operator_0_statepreparation_4_rygate_3_mcx_0_140387288350992 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387288364496_o1 q0,q1,q2;
}

gate c_operator_1_statepreparation_8_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_4_rygate_3_mcx_0_140387288350992 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_4_rygate_3_mcx_0_140387288350992 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387288355536 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387288355536_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387288355536 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140387288363152 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387288355536_o0 q0,q1;
}

gate c_operator_1_statepreparation_8_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387288363152 q1,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387288363152 q1,q0;
  ry(pi/2) q0;
}

gate c_operator_1_statepreparation_8 q0,q1,q2 {
  ry(pi/2) q2;
  c_operator_1_statepreparation_8_rygate_1 q1,q2;
  c_operator_1_statepreparation_8_rygate_2 q0,q1,q2;
  c_operator_1_statepreparation_8_rygate_3 q1,q2;
  c_operator_1_statepreparation_8_rygate_4 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387459218000 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387459218000_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387459218000 q0,q1;
  x q0;
}

gate c_operator_1_statepreparation_7_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387459218000_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387875498128 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387875498128_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387875498128 q0,q1;
  x q0;
}

gate c_operator_1_statepreparation_7_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387875498128_o0 q0,q1;
}

gate c_operator_1_statepreparation_7_rygate_0_qinverse q0,q1 {
  ry(-pi/2) q0;
  c_operator_1_statepreparation_7_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/2) q0;
  c_operator_1_statepreparation_7_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate c_operator_1_statepreparation_7 q0,q1,q2 {
  c_operator_1_statepreparation_7_rygate_0_qinverse q1,q2;
  ry(-pi/2) q2;
}

gate c_operator_1_zero_diffuzer_3_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387169389008 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387804825872 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387169389008 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387169389008 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387804826512 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387804825872 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_3 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387804826512 q0,q1,q2,q6,q7;
  c_operator_1_zero_diffuzer_3_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387804826512 q0,q1,q2,q6,q9;
}

gate c_operator_1_inplace_prepare_int_6 q0,q1,q2 {
  x q2;
}

gate c_operator_1_inplace_prepare_int_5 q0,q1,q2 {
  x q2;
  x q0;
}

gate mcx_hybrid_gray_code_maslov15_140388313555984 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140388313555984_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140388313555984 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140388313556112 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388313555984_o0 q0,q1;
}

gate c_operator_1_statepreparation_6_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140388313556112 q1,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140388313556112 q1,q0;
  ry(pi/2) q0;
}

gate c_operator_1_statepreparation_6 q0,q1,q2 {
  ry(pi/2) q2;
  c_operator_1_statepreparation_6_rygate_1 q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387954672080 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387954672080_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387954672080 q0,q1;
  x q0;
}

gate c_operator_1_statepreparation_5_rygate_2_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387954672080_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387732974608 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387732974608_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387732974608 q0,q1;
  x q0;
}

gate c_operator_1_statepreparation_5_rygate_2_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387732974608_o0 q0,q1;
}

gate c_operator_1_statepreparation_5_rygate_2_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_1_statepreparation_5_rygate_2_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_1_statepreparation_5_rygate_2_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387149278416 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387149278416_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140387149278416 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_1_statepreparation_5_rygate_1_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387149278416_o0 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387149276176 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387149276176_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140387149276176 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_1_statepreparation_5_rygate_1_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387149276176_o0 q0,q1,q2;
}

gate c_operator_1_statepreparation_5_rygate_1_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_1_statepreparation_5_rygate_1_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_1_statepreparation_5_rygate_1_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387149270096 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387149270096_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387149270096 q0,q1,q2;
  x q1;
}

gate c_operator_1_statepreparation_5_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387149270096_o1 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387149268880 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387149268880_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387149268880 q0,q1,q2;
  x q1;
}

gate c_operator_1_statepreparation_5_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387149268880_o1 q0,q1,q2;
}

gate c_operator_1_statepreparation_5_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_1_statepreparation_5_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_1_statepreparation_5_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_1_statepreparation_5 q0,q1,q2 {
  c_operator_1_statepreparation_5_rygate_0_qinverse q0,q1,q2;
  c_operator_1_statepreparation_5_rygate_1_qinverse q0,q1,q2;
  c_operator_1_statepreparation_5_rygate_2_qinverse q1,q2;
  ry(0) q2;
}

gate c_operator_1_zero_diffuzer_2_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140388986680016 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387345824400 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140388986680016 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140388986680016 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387345809744 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387345824400 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_2 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387345809744 q0,q1,q2,q6,q7;
  c_operator_1_zero_diffuzer_2_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387345809744 q0,q1,q2,q6,q9;
}

gate c_operator_1_inplace_prepare_int_4 q0,q1,q2 {
  x q0;
  x q2;
}

gate c_operator_1_inplace_prepare_int_3 q0,q1,q2 {
  x q2;
  x q1;
}

gate mcx_hybrid_gray_code_maslov15_140387466775120 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387466775120_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387466775120 q0,q1,q2;
  x q1;
}

gate c_operator_0_statepreparation_4_rygate_3_mcx_0_140387466772816 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387466775120_o1 q0,q1,q2;
}

gate c_operator_1_statepreparation_4_rygate_3 q0,q1,q2 {
  c_operator_0_statepreparation_4_rygate_3_mcx_0_140387466772816 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_4_rygate_3_mcx_0_140387466772816 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387466778320 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387466778320_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140387466778320 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_0_statepreparation_4_rygate_2_mcx_0_140387466783312 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387466778320_o0 q0,q1,q2;
}

gate c_operator_1_statepreparation_4_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_4_rygate_2_mcx_0_140387466783312 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_4_rygate_2_mcx_0_140387466783312 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387466773328 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387466773328_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387466773328 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140387466777680 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387466773328_o0 q0,q1;
}

gate c_operator_1_statepreparation_4_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387466777680 q1,q0;
  ry(-pi/4) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387466777680 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_1_statepreparation_4 q0,q1,q2 {
  ry(0) q2;
  c_operator_1_statepreparation_4_rygate_1 q1,q2;
  c_operator_1_statepreparation_4_rygate_2 q0,q1,q2;
  c_operator_1_statepreparation_4_rygate_3 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387466777232 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387466777232_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387466777232 q0,q1;
  x q0;
}

gate c_operator_1_statepreparation_3_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387466777232_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387466774416 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387466774416_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387466774416 q0,q1;
  x q0;
}

gate c_operator_1_statepreparation_3_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387466774416_o0 q0,q1;
}

gate c_operator_1_statepreparation_3_rygate_0_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_1_statepreparation_3_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_1_statepreparation_3_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate c_operator_1_statepreparation_3 q0,q1,q2 {
  c_operator_1_statepreparation_3_rygate_0_qinverse q1,q2;
  ry(0) q2;
}

gate c_operator_1_zero_diffuzer_1_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387514344656 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387467381136 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387514344656 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387514344656 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387467380048 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387467381136 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_1 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387467380048 q0,q1,q2,q6,q7;
  c_operator_1_zero_diffuzer_1_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387467380048 q0,q1,q2,q6,q9;
}

gate c_operator_1_inplace_prepare_int_2 q0,q1,q2 {
  x q1;
  x q2;
}

gate c_operator_1_inplace_prepare_int_1 q0,q1,q2 {
  x q2;
  x q1;
  x q0;
}

gate mcx_hybrid_gray_code_maslov15_140387307609872 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387307609872_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387307609872 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140387307603792 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387307609872_o0 q0,q1;
}

gate c_operator_1_statepreparation_2_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387307603792 q1,q0;
  ry(-pi/4) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387307603792 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_1_statepreparation_2 q0,q1,q2 {
  ry(0) q2;
  c_operator_1_statepreparation_2_rygate_1 q1,q2;
}

gate c_operator_1_statepreparation_1_computationalbasisstatepreparation_qinverse q0,q1,q2 {
  x q0;
}

gate c_operator_1_statepreparation_1 q0,q1,q2 {
  c_operator_1_statepreparation_1_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_1_zero_diffuzer_0_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387466692816 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140388299904208 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387466692816 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387466692816 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140388299905104 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140388299904208 q0,q1,q2,q3,q4;
}

gate c_operator_1_zero_diffuzer_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140388299905104 q0,q1,q2,q6,q7;
  c_operator_1_zero_diffuzer_0_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140388299905104 q0,q1,q2,q6,q9;
}

gate c_operator_1_inplace_prepare_int_0 q0,q1,q2 {
  x q0;
  x q1;
  x q2;
}

gate c_operator_0_statepreparation_0_computationalbasisstatepreparation_140387461710800 q0,q1,q2 {
  x q0;
}

gate c_operator_1_statepreparation_0 q0,q1,q2 {
  c_operator_0_statepreparation_0_computationalbasisstatepreparation_140387461710800 q0,q1,q2;
}

gate cbitwise_swap_expanded___54 q0,q1,q2,q3,q4,q5,q6 {
  cswap q0,q1,q4;
  cswap q0,q2,q5;
  cswap q0,q3,q6;
}

gate s_operator_0_bitwise_swap q0,q1,q2,q3,q4,q5,q6 {
  cbitwise_swap_expanded___54 q0,q1,q2,q3,q4,q5,q6;
}

gate s_operator_0_edge_oracle_arithmetic_adder_1 q0,q1,q2,q3,q4,q5 {
  cx q3,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387459013776 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387459007440 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387459013776 q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387459007440 q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_adder_0 q0,q1,q2,q3,q4,q5 {
  cx q3,q0;
}

gate s_operator_0_edge_oracle_arithmetic q0,q1,q2,q3,q4,q5,q6 {
  s_operator_0_edge_oracle_arithmetic_adder_0 q0,q1,q2,q3,q4,q5;
  s_operator_0_edge_oracle_arithmetic_equal q0,q6;
  s_operator_0_edge_oracle_arithmetic_adder_1 q0,q1,q2,q3,q4,q5;
}

gate s_operator_0_edge_oracle q0,q1,q2,q3,q4,q5,q6 {
  s_operator_0_edge_oracle_arithmetic q0,q1,q2,q3,q4,q5,q6;
}

gate c_operator_0_statepreparation_15_computationalbasisstatepreparation_qinverse q0,q1,q2 {
  x q2;
  x q1;
}

gate c_operator_0_statepreparation_15 q0,q1,q2 {
  c_operator_0_statepreparation_15_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_0_zero_diffuzer_7_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387461824656 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387459016720 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387461824656 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387461824656 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387459016976 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387459016720 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_7 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387459016976 q0,q1,q2,q4,q3;
  c_operator_0_zero_diffuzer_7_zero_diffuzer_aux_control_name q4,q5,q6,q7,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387459016976 q0,q1,q2,q4,q9;
}

gate c_operator_0_inplace_prepare_int_13 q0,q1,q2 {
  x q0;
}

gate c_operator_0_statepreparation_14_computationalbasisstatepreparation q0,q1,q2 {
  x q1;
  x q2;
}

gate c_operator_0_statepreparation_14 q0,q1,q2 {
  c_operator_0_statepreparation_14_computationalbasisstatepreparation q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387460694544 q0,q1 {
  cx q0,q1;
}

gate c_operator_0_statepreparation_13_rygate_2_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387460694544 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387459804624 q0,q1 {
  cx q0,q1;
}

gate c_operator_0_statepreparation_13_rygate_2_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387459804624 q0,q1;
}

gate c_operator_0_statepreparation_13_rygate_2_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_0_statepreparation_13_rygate_2_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_0_statepreparation_13_rygate_2_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387459806992 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387459806992_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387459806992 q0,q1,q2;
  x q0;
}

gate c_operator_0_statepreparation_13_rygate_1_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387459806992_o2 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387459803088 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387459803088_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387459803088 q0,q1,q2;
  x q0;
}

gate c_operator_0_statepreparation_13_rygate_1_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387459803088_o2 q0,q1,q2;
}

gate c_operator_0_statepreparation_13_rygate_1_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_0_statepreparation_13_rygate_1_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_0_statepreparation_13_rygate_1_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387459265744 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate c_operator_0_statepreparation_13_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387459265744 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387511238352 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate c_operator_0_statepreparation_13_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387511238352 q0,q1,q2;
}

gate c_operator_0_statepreparation_13_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_0_statepreparation_13_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_0_statepreparation_13_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_0_statepreparation_13 q0,q1,q2 {
  c_operator_0_statepreparation_13_rygate_0_qinverse q0,q1,q2;
  c_operator_0_statepreparation_13_rygate_1_qinverse q0,q1,q2;
  c_operator_0_statepreparation_13_rygate_2_qinverse q1,q2;
  ry(-pi) q2;
}

gate c_operator_0_zero_diffuzer_6_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387459540688 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387135652304 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387459540688 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387459540688 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387135659664 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387135652304 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_6 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387135659664 q0,q1,q2,q8,q9;
  c_operator_0_zero_diffuzer_6_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387135659664 q0,q1,q2,q8,q7;
}

gate c_operator_0_inplace_prepare_int_12 q0,q1,q2 {
  x q0;
}

gate c_operator_0_inplace_prepare_int_11 q0,q1,q2 {
  x q1;
}

gate mcx_hybrid_gray_code_maslov15_140387717571152 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate c_operator_0_statepreparation_12_rygate_3_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387717571152 q0,q1,q2;
}

gate c_operator_0_statepreparation_12_rygate_3 q0,q1,q2 {
  c_operator_0_statepreparation_12_rygate_3_mcx_0 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_12_rygate_3_mcx_0 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140388381381456 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388381381456_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140388381381456 q0,q1,q2;
  x q0;
}

gate c_operator_0_statepreparation_8_rygate_4_mcx_0_140388381392784 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140388381381456_o2 q0,q1,q2;
}

gate c_operator_0_statepreparation_12_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_8_rygate_4_mcx_0_140388381392784 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_8_rygate_4_mcx_0_140388381392784 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140388322797776 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140388322802192 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388322797776 q0,q1;
}

gate c_operator_0_statepreparation_12_rygate_1 q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140388322802192 q1,q0;
  ry(-pi/4) q0;
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140388322802192 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_0_statepreparation_12 q0,q1,q2 {
  ry(pi) q2;
  c_operator_0_statepreparation_12_rygate_1 q1,q2;
  c_operator_0_statepreparation_12_rygate_2 q0,q1,q2;
  c_operator_0_statepreparation_12_rygate_3 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388322797968 q0,q1 {
  cx q0,q1;
}

gate c_operator_0_statepreparation_11_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388322797968 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140388322799376 q0,q1 {
  cx q0,q1;
}

gate c_operator_0_statepreparation_11_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388322799376 q0,q1;
}

gate c_operator_0_statepreparation_11_rygate_0_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_0_statepreparation_11_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_0_statepreparation_11_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate c_operator_0_statepreparation_11 q0,q1,q2 {
  c_operator_0_statepreparation_11_rygate_0_qinverse q1,q2;
  ry(-pi) q2;
}

gate c_operator_0_zero_diffuzer_5_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387459235792 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387255053200 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387459235792 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387459235792 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387255045648 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387255053200 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_5 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387255045648 q0,q1,q2,q6,q7;
  c_operator_0_zero_diffuzer_5_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387255045648 q0,q1,q2,q6,q9;
}

gate c_operator_0_inplace_prepare_int_10 q0,q1,q2 {
  x q1;
}

gate c_operator_0_inplace_prepare_int_9 q0,q1,q2 {
  x q1;
  x q0;
}

gate mcx_hybrid_gray_code_maslov15_140387254713168 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387254708112 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387254713168 q0,q1;
}

gate c_operator_0_statepreparation_10_rygate_1 q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387254708112 q1,q0;
  ry(-pi/4) q0;
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0_140387254708112 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_0_statepreparation_10 q0,q1,q2 {
  ry(pi) q2;
  c_operator_0_statepreparation_10_rygate_1 q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387161032592 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387161032592_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387161032592 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_9_rygate_3_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387161032592_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387161046544 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387161046544_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387161046544 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_9_rygate_3_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387161046544_o0 q0,q1;
}

gate c_operator_0_statepreparation_9_rygate_3_qinverse q0,q1 {
  ry(-pi/2) q0;
  c_operator_0_statepreparation_9_rygate_3_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/2) q0;
  c_operator_0_statepreparation_9_rygate_3_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387161034448 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387161034448_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387161034448 q0,q1,q2;
  x q1;
}

gate c_operator_0_statepreparation_9_rygate_2_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387161034448_o1 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387161038928 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387161038928_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387161038928 q0,q1,q2;
  x q1;
}

gate c_operator_0_statepreparation_9_rygate_2_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387161038928_o1 q0,q1,q2;
}

gate c_operator_0_statepreparation_9_rygate_2_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_0_statepreparation_9_rygate_2_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_0_statepreparation_9_rygate_2_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387161040528 q0,q1 {
  cx q0,q1;
}

gate c_operator_0_statepreparation_9_rygate_1_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387161040528 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387161034128 q0,q1 {
  cx q0,q1;
}

gate c_operator_0_statepreparation_9_rygate_1_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387161034128 q0,q1;
}

gate c_operator_0_statepreparation_9_rygate_1_qinverse q0,q1 {
  c_operator_0_statepreparation_9_rygate_1_qinverse_mcx_0_qinverse q1,q0;
  c_operator_0_statepreparation_9_rygate_1_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387161036368 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387161036368_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387161036368 q0,q1,q2;
  x q0;
}

gate c_operator_0_statepreparation_9_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387161036368_o2 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387161039824 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387161039824_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387161039824 q0,q1,q2;
  x q0;
}

gate c_operator_0_statepreparation_9_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387161039824_o2 q0,q1,q2;
}

gate c_operator_0_statepreparation_9_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_0_statepreparation_9_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_0_statepreparation_9_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_0_statepreparation_9 q0,q1,q2 {
  c_operator_0_statepreparation_9_rygate_0_qinverse q0,q1,q2;
  c_operator_0_statepreparation_9_rygate_1_qinverse q1,q2;
  c_operator_0_statepreparation_9_rygate_2_qinverse q0,q1,q2;
  c_operator_0_statepreparation_9_rygate_3_qinverse q1,q2;
  ry(-pi/2) q2;
}

gate c_operator_0_zero_diffuzer_4_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387254700560 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140388945088656 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387254700560 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387254700560 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140388945090448 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140388945088656 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_4 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140388945090448 q0,q1,q2,q6,q7;
  c_operator_0_zero_diffuzer_4_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140388945090448 q0,q1,q2,q6,q9;
}

gate c_operator_0_inplace_prepare_int_8 q0,q1,q2 {
  x q0;
  x q1;
}

gate c_operator_0_inplace_prepare_int_7 q0,q1,q2 {
  x q2;
}

gate mcx_hybrid_gray_code_maslov15_140387414722000 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387414722000_o2 q0,q1,q2 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387414722000 q0,q1,q2;
  x q0;
}

gate c_operator_0_statepreparation_8_rygate_4_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387414722000_o2 q0,q1,q2;
}

gate c_operator_0_statepreparation_8_rygate_4 q0,q1,q2 {
  c_operator_0_statepreparation_8_rygate_4_mcx_0 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_8_rygate_4_mcx_0 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140388987742480 q0,q1 {
  cx q0,q1;
}

gate s_operator_0_edge_oracle_arithmetic_equal_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388987742480 q0,q1;
}

gate c_operator_0_statepreparation_8_rygate_3 q0,q1 {
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0 q1,q0;
  s_operator_0_edge_oracle_arithmetic_equal_mcx_0 q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387244132688 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387244132688_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387244132688 q0,q1,q2;
  x q1;
}

gate c_operator_0_statepreparation_4_rygate_3_mcx_0_140387449854224 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387244132688_o1 q0,q1,q2;
}

gate c_operator_0_statepreparation_8_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_4_rygate_3_mcx_0_140387449854224 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_4_rygate_3_mcx_0_140387449854224 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387449849680 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387449849680_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387449849680 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140387449862288 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387449849680_o0 q0,q1;
}

gate c_operator_0_statepreparation_8_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387449862288 q1,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387449862288 q1,q0;
  ry(pi/2) q0;
}

gate c_operator_0_statepreparation_8 q0,q1,q2 {
  ry(pi/2) q2;
  c_operator_0_statepreparation_8_rygate_1 q1,q2;
  c_operator_0_statepreparation_8_rygate_2 q0,q1,q2;
  c_operator_0_statepreparation_8_rygate_3 q1,q2;
  c_operator_0_statepreparation_8_rygate_4 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140388035586320 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140388035586320_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140388035586320 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_7_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388035586320_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140388035578384 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140388035578384_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140388035578384 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_7_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140388035578384_o0 q0,q1;
}

gate c_operator_0_statepreparation_7_rygate_0_qinverse q0,q1 {
  ry(-pi/2) q0;
  c_operator_0_statepreparation_7_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/2) q0;
  c_operator_0_statepreparation_7_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate c_operator_0_statepreparation_7 q0,q1,q2 {
  c_operator_0_statepreparation_7_rygate_0_qinverse q1,q2;
  ry(-pi/2) q2;
}

gate c_operator_0_zero_diffuzer_3_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387457195792 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387244138960 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387457195792 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387457195792 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387244131920 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387244138960 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_3 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387244131920 q0,q1,q2,q6,q7;
  c_operator_0_zero_diffuzer_3_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387244131920 q0,q1,q2,q6,q9;
}

gate c_operator_0_inplace_prepare_int_6 q0,q1,q2 {
  x q2;
}

gate c_operator_0_inplace_prepare_int_5 q0,q1,q2 {
  x q2;
  x q0;
}

gate mcx_hybrid_gray_code_maslov15_140387361226192 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387361226192_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387361226192 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140387361225552 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387361226192_o0 q0,q1;
}

gate c_operator_0_statepreparation_6_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387361225552 q1,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387361225552 q1,q0;
  ry(pi/2) q0;
}

gate c_operator_0_statepreparation_6 q0,q1,q2 {
  ry(pi/2) q2;
  c_operator_0_statepreparation_6_rygate_1 q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387361226064 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387361226064_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387361226064 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_5_rygate_2_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387361226064_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387355547408 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387355547408_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387355547408 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_5_rygate_2_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387355547408_o0 q0,q1;
}

gate c_operator_0_statepreparation_5_rygate_2_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_0_statepreparation_5_rygate_2_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_0_statepreparation_5_rygate_2_qinverse_mcx_1_qinverse q1,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387292756176 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387292756176_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140387292756176 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_0_statepreparation_5_rygate_1_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387292756176_o0 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387292752656 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387292752656_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140387292752656 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_0_statepreparation_5_rygate_1_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387292752656_o0 q0,q1,q2;
}

gate c_operator_0_statepreparation_5_rygate_1_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_0_statepreparation_5_rygate_1_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_0_statepreparation_5_rygate_1_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate mcx_hybrid_gray_code_maslov15_140387292750480 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387292750480_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387292750480 q0,q1,q2;
  x q1;
}

gate c_operator_0_statepreparation_5_rygate_0_qinverse_mcx_1_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387292750480_o1 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387238200656 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387238200656_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387238200656 q0,q1,q2;
  x q1;
}

gate c_operator_0_statepreparation_5_rygate_0_qinverse_mcx_0_qinverse q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387238200656_o1 q0,q1,q2;
}

gate c_operator_0_statepreparation_5_rygate_0_qinverse q0,q1,q2 {
  ry(-pi/2) q0;
  c_operator_0_statepreparation_5_rygate_0_qinverse_mcx_0_qinverse q1,q2,q0;
  ry(pi/2) q0;
  c_operator_0_statepreparation_5_rygate_0_qinverse_mcx_1_qinverse q1,q2,q0;
}

gate c_operator_0_statepreparation_5 q0,q1,q2 {
  c_operator_0_statepreparation_5_rygate_0_qinverse q0,q1,q2;
  c_operator_0_statepreparation_5_rygate_1_qinverse q0,q1,q2;
  c_operator_0_statepreparation_5_rygate_2_qinverse q1,q2;
  ry(0) q2;
}

gate c_operator_0_zero_diffuzer_2_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387449849872 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387355554832 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387449849872 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387449849872 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387355550352 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387355554832 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_2 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387355550352 q0,q1,q2,q6,q7;
  c_operator_0_zero_diffuzer_2_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387355550352 q0,q1,q2,q6,q9;
}

gate c_operator_0_inplace_prepare_int_4 q0,q1,q2 {
  x q0;
  x q2;
}

gate c_operator_0_inplace_prepare_int_3 q0,q1,q2 {
  x q2;
  x q1;
}

gate mcx_hybrid_gray_code_maslov15_140387411241168 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387411241168_o1 q0,q1,q2 {
  x q1;
  mcx_hybrid_gray_code_maslov15_140387411241168 q0,q1,q2;
  x q1;
}

gate c_operator_0_statepreparation_4_rygate_3_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387411241168_o1 q0,q1,q2;
}

gate c_operator_0_statepreparation_4_rygate_3 q0,q1,q2 {
  c_operator_0_statepreparation_4_rygate_3_mcx_0 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_4_rygate_3_mcx_0 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387315590928 q0,q1,q2 {
  ccx q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387315590928_o0 q0,q1,q2 {
  x q0;
  x q1;
  mcx_hybrid_gray_code_maslov15_140387315590928 q0,q1,q2;
  x q0;
  x q1;
}

gate c_operator_0_statepreparation_4_rygate_2_mcx_0 q0,q1,q2 {
  mcx_hybrid_gray_code_maslov15_140387315590928_o0 q0,q1,q2;
}

gate c_operator_0_statepreparation_4_rygate_2 q0,q1,q2 {
  c_operator_0_statepreparation_4_rygate_2_mcx_0 q1,q2,q0;
  ry(-pi/2) q0;
  c_operator_0_statepreparation_4_rygate_2_mcx_0 q1,q2,q0;
  ry(pi/2) q0;
}

gate mcx_hybrid_gray_code_maslov15_140387178733008 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387178733008_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387178733008 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0_140387323163344 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387178733008_o0 q0,q1;
}

gate c_operator_0_statepreparation_4_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387323163344 q1,q0;
  ry(-pi/4) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0_140387323163344 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_0_statepreparation_4 q0,q1,q2 {
  ry(0) q2;
  c_operator_0_statepreparation_4_rygate_1 q1,q2;
  c_operator_0_statepreparation_4_rygate_2 q0,q1,q2;
  c_operator_0_statepreparation_4_rygate_3 q0,q1,q2;
}

gate mcx_hybrid_gray_code_maslov15_140387279813328 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387279813328_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387279813328 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_3_rygate_0_qinverse_mcx_1_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387279813328_o0 q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387279804944 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387279804944_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387279804944 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_3_rygate_0_qinverse_mcx_0_qinverse q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387279804944_o0 q0,q1;
}

gate c_operator_0_statepreparation_3_rygate_0_qinverse q0,q1 {
  ry(-pi/4) q0;
  c_operator_0_statepreparation_3_rygate_0_qinverse_mcx_0_qinverse q1,q0;
  ry(pi/4) q0;
  c_operator_0_statepreparation_3_rygate_0_qinverse_mcx_1_qinverse q1,q0;
}

gate c_operator_0_statepreparation_3 q0,q1,q2 {
  c_operator_0_statepreparation_3_rygate_0_qinverse q1,q2;
  ry(0) q2;
}

gate c_operator_0_zero_diffuzer_1_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888_140387238212368 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15_140387279811280 q0,q1,q2,q3,q4 {
  r1tof_140390385447888_140387238212368 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888_140387238212368 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0_140387279806928 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15_140387279811280 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_1 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0_140387279806928 q0,q1,q2,q6,q7;
  c_operator_0_zero_diffuzer_1_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0_140387279806928 q0,q1,q2,q6,q9;
}

gate c_operator_0_inplace_prepare_int_2 q0,q1,q2 {
  x q1;
  x q2;
}

gate c_operator_0_inplace_prepare_int_1 q0,q1,q2 {
  x q2;
  x q1;
  x q0;
}

gate mcx_hybrid_gray_code_maslov15_140387411536976 q0,q1 {
  cx q0,q1;
}

gate mcx_hybrid_gray_code_maslov15_140387411536976_o0 q0,q1 {
  x q0;
  mcx_hybrid_gray_code_maslov15_140387411536976 q0,q1;
  x q0;
}

gate c_operator_0_statepreparation_2_rygate_1_mcx_0 q0,q1 {
  mcx_hybrid_gray_code_maslov15_140387411536976_o0 q0,q1;
}

gate c_operator_0_statepreparation_2_rygate_1 q0,q1 {
  c_operator_0_statepreparation_2_rygate_1_mcx_0 q1,q0;
  ry(-pi/4) q0;
  c_operator_0_statepreparation_2_rygate_1_mcx_0 q1,q0;
  ry(pi/4) q0;
}

gate c_operator_0_statepreparation_2 q0,q1,q2 {
  ry(0) q2;
  c_operator_0_statepreparation_2_rygate_1 q1,q2;
}

gate c_operator_0_statepreparation_1_computationalbasisstatepreparation_qinverse q0,q1,q2 {
  x q0;
}

gate c_operator_0_statepreparation_1 q0,q1,q2 {
  c_operator_0_statepreparation_1_computationalbasisstatepreparation_qinverse q0,q1,q2;
}

gate c_operator_0_zero_diffuzer_0_zero_diffuzer_aux_control_name q0,q1,q2,q3,q4 {
}

gate r1tof_140390385447888 q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate mcx_hybrid_gray_code_maslov15 q0,q1,q2,q3,q4 {
  r1tof_140390385447888 q0,q1,q4;
  ccx q4,q2,q3;
  r1tof_140390385447888 q0,q1,q4;
}

gate c_operator_0_zero_diffuzer_0_mcx_0 q0,q1,q2,q3,q4 {
  mcx_hybrid_gray_code_maslov15 q0,q1,q2,q3,q4;
}

gate c_operator_0_zero_diffuzer_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9 {
  c_operator_0_zero_diffuzer_0_mcx_0 q0,q1,q2,q6,q7;
  c_operator_0_zero_diffuzer_0_zero_diffuzer_aux_control_name q3,q4,q5,q6,q8;
  c_operator_0_zero_diffuzer_0_mcx_0 q0,q1,q2,q6,q9;
}

gate c_operator_0_inplace_prepare_int_0 q0,q1,q2 {
  x q0;
  x q1;
  x q2;
}

gate c_operator_0_statepreparation_0_computationalbasisstatepreparation q0,q1,q2 {
  x q0;
}

gate c_operator_0_statepreparation_0 q0,q1,q2 {
  c_operator_0_statepreparation_0_computationalbasisstatepreparation q0,q1,q2;
}

gate apply_to_all_expanded___3 q0,q1,q2 {
  h q0;
  h q1;
  h q2;
}

gate main_hadamard_transform q0,q1,q2 {
  apply_to_all_expanded___3 q0,q1,q2;
}

gate main_c_operator_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37 {
  c_operator_0_statepreparation_0 q3,q4,q5;
  c_operator_0_inplace_prepare_int_0 q0,q1,q2;
  c_operator_0_zero_diffuzer_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
  c_operator_0_statepreparation_1 q3,q4,q5;
  c_operator_0_statepreparation_2 q3,q4,q5;
  c_operator_0_inplace_prepare_int_1 q0,q1,q2;
  c_operator_0_inplace_prepare_int_2 q0,q1,q2;
  c_operator_0_zero_diffuzer_1 q0,q1,q2,q3,q4,q5,q10,q11,q12,q13;
  c_operator_0_statepreparation_3 q3,q4,q5;
  c_operator_0_statepreparation_4 q3,q4,q5;
  c_operator_0_inplace_prepare_int_3 q0,q1,q2;
  c_operator_0_inplace_prepare_int_4 q0,q1,q2;
  c_operator_0_zero_diffuzer_2 q0,q1,q2,q3,q4,q5,q14,q15,q16,q17;
  c_operator_0_statepreparation_5 q3,q4,q5;
  c_operator_0_statepreparation_6 q3,q4,q5;
  c_operator_0_inplace_prepare_int_5 q0,q1,q2;
  c_operator_0_inplace_prepare_int_6 q0,q1,q2;
  c_operator_0_zero_diffuzer_3 q0,q1,q2,q3,q4,q5,q18,q19,q20,q21;
  c_operator_0_statepreparation_7 q3,q4,q5;
  c_operator_0_statepreparation_8 q3,q4,q5;
  c_operator_0_inplace_prepare_int_7 q0,q1,q2;
  c_operator_0_inplace_prepare_int_8 q0,q1,q2;
  c_operator_0_zero_diffuzer_4 q0,q1,q2,q3,q4,q5,q22,q23,q24,q25;
  c_operator_0_statepreparation_9 q3,q4,q5;
  c_operator_0_statepreparation_10 q3,q4,q5;
  c_operator_0_inplace_prepare_int_9 q0,q1,q2;
  c_operator_0_inplace_prepare_int_10 q0,q1,q2;
  c_operator_0_zero_diffuzer_5 q0,q1,q2,q3,q4,q5,q26,q27,q28,q29;
  c_operator_0_statepreparation_11 q3,q4,q5;
  c_operator_0_statepreparation_12 q3,q4,q5;
  c_operator_0_inplace_prepare_int_11 q0,q1,q2;
  c_operator_0_inplace_prepare_int_12 q0,q1,q2;
  c_operator_0_zero_diffuzer_6 q0,q1,q2,q32,q3,q4,q5,q33,q30,q31;
  c_operator_0_statepreparation_13 q3,q4,q5;
  c_operator_0_statepreparation_14 q3,q4,q5;
  c_operator_0_inplace_prepare_int_13 q0,q1,q2;
  c_operator_0_zero_diffuzer_7 q0,q1,q2,q35,q34,q3,q36,q5,q4,q37;
  c_operator_0_statepreparation_15 q3,q4,q5;
}

gate main_s_operator_0 q0,q1,q2,q3,q4,q5,q6 {
  s_operator_0_edge_oracle q0,q1,q2,q3,q4,q5,q6;
  s_operator_0_bitwise_swap q6,q0,q1,q2,q3,q4,q5;
}

gate main_c_operator_1 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37 {
  c_operator_1_statepreparation_0 q3,q4,q5;
  c_operator_1_inplace_prepare_int_0 q0,q1,q2;
  c_operator_1_zero_diffuzer_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
  c_operator_1_statepreparation_1 q3,q4,q5;
  c_operator_1_statepreparation_2 q3,q4,q5;
  c_operator_1_inplace_prepare_int_1 q0,q1,q2;
  c_operator_1_inplace_prepare_int_2 q0,q1,q2;
  c_operator_1_zero_diffuzer_1 q0,q1,q2,q3,q4,q5,q10,q11,q12,q13;
  c_operator_1_statepreparation_3 q3,q4,q5;
  c_operator_1_statepreparation_4 q3,q4,q5;
  c_operator_1_inplace_prepare_int_3 q0,q1,q2;
  c_operator_1_inplace_prepare_int_4 q0,q1,q2;
  c_operator_1_zero_diffuzer_2 q0,q1,q2,q3,q4,q5,q14,q15,q16,q17;
  c_operator_1_statepreparation_5 q3,q4,q5;
  c_operator_1_statepreparation_6 q3,q4,q5;
  c_operator_1_inplace_prepare_int_5 q0,q1,q2;
  c_operator_1_inplace_prepare_int_6 q0,q1,q2;
  c_operator_1_zero_diffuzer_3 q0,q1,q2,q3,q4,q5,q18,q19,q20,q21;
  c_operator_1_statepreparation_7 q3,q4,q5;
  c_operator_1_statepreparation_8 q3,q4,q5;
  c_operator_1_inplace_prepare_int_7 q0,q1,q2;
  c_operator_1_inplace_prepare_int_8 q0,q1,q2;
  c_operator_1_zero_diffuzer_4 q0,q1,q2,q3,q4,q5,q22,q23,q24,q25;
  c_operator_1_statepreparation_9 q3,q4,q5;
  c_operator_1_statepreparation_10 q3,q4,q5;
  c_operator_1_inplace_prepare_int_9 q0,q1,q2;
  c_operator_1_inplace_prepare_int_10 q0,q1,q2;
  c_operator_1_zero_diffuzer_5 q0,q1,q2,q3,q4,q5,q26,q27,q28,q29;
  c_operator_1_statepreparation_11 q3,q4,q5;
  c_operator_1_statepreparation_12 q3,q4,q5;
  c_operator_1_inplace_prepare_int_11 q0,q1,q2;
  c_operator_1_inplace_prepare_int_12 q0,q1,q2;
  c_operator_1_zero_diffuzer_6 q0,q1,q2,q31,q32,q3,q4,q5,q33,q30;
  c_operator_1_statepreparation_13 q3,q4,q5;
  c_operator_1_statepreparation_14 q3,q4,q5;
  c_operator_1_inplace_prepare_int_13 q0,q1,q2;
  c_operator_1_zero_diffuzer_7 q0,q1,q2,q34,q35,q3,q5,q4,q36,q37;
  c_operator_1_statepreparation_15 q3,q4,q5;
}

gate main_s_operator_1 q0,q1,q2,q3,q4,q5,q6 {
  s_operator_1_edge_oracle q0,q1,q2,q3,q4,q5,q6;
  s_operator_1_bitwise_swap q6,q0,q1,q2,q3,q4,q5;
}

gate main_c_operator_2 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37 {
  c_operator_2_statepreparation_0 q3,q4,q5;
  c_operator_2_inplace_prepare_int_0 q0,q1,q2;
  c_operator_2_zero_diffuzer_0 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9;
  c_operator_2_statepreparation_1 q3,q4,q5;
  c_operator_2_statepreparation_2 q3,q4,q5;
  c_operator_2_inplace_prepare_int_1 q0,q1,q2;
  c_operator_2_inplace_prepare_int_2 q0,q1,q2;
  c_operator_2_zero_diffuzer_1 q0,q1,q2,q3,q4,q5,q10,q11,q12,q13;
  c_operator_2_statepreparation_3 q3,q4,q5;
  c_operator_2_statepreparation_4 q3,q4,q5;
  c_operator_2_inplace_prepare_int_3 q0,q1,q2;
  c_operator_2_inplace_prepare_int_4 q0,q1,q2;
  c_operator_2_zero_diffuzer_2 q0,q1,q2,q3,q4,q5,q14,q15,q16,q17;
  c_operator_2_statepreparation_5 q3,q4,q5;
  c_operator_2_statepreparation_6 q3,q4,q5;
  c_operator_2_inplace_prepare_int_5 q0,q1,q2;
  c_operator_2_inplace_prepare_int_6 q0,q1,q2;
  c_operator_2_zero_diffuzer_3 q0,q1,q2,q3,q4,q5,q18,q19,q20,q21;
  c_operator_2_statepreparation_7 q3,q4,q5;
  c_operator_2_statepreparation_8 q3,q4,q5;
  c_operator_2_inplace_prepare_int_7 q0,q1,q2;
  c_operator_2_inplace_prepare_int_8 q0,q1,q2;
  c_operator_2_zero_diffuzer_4 q0,q1,q2,q3,q4,q5,q22,q23,q24,q25;
  c_operator_2_statepreparation_9 q3,q4,q5;
  c_operator_2_statepreparation_10 q3,q4,q5;
  c_operator_2_inplace_prepare_int_9 q0,q1,q2;
  c_operator_2_inplace_prepare_int_10 q0,q1,q2;
  c_operator_2_zero_diffuzer_5 q0,q1,q2,q3,q4,q5,q26,q27,q28,q29;
  c_operator_2_statepreparation_11 q3,q4,q5;
  c_operator_2_statepreparation_12 q3,q4,q5;
  c_operator_2_inplace_prepare_int_11 q0,q1,q2;
  c_operator_2_inplace_prepare_int_12 q0,q1,q2;
  c_operator_2_zero_diffuzer_6 q0,q1,q2,q30,q31,q32,q3,q4,q5,q33;
  c_operator_2_statepreparation_13 q3,q4,q5;
  c_operator_2_statepreparation_14 q3,q4,q5;
  c_operator_2_inplace_prepare_int_13 q0,q1,q2;
  c_operator_2_zero_diffuzer_7 q0,q1,q2,q3,q34,q35,q5,q4,q36,q37;
  c_operator_2_statepreparation_15 q3,q4,q5;
}

gate main_s_operator_2 q0,q1,q2,q3,q4,q5,q6 {
  s_operator_2_edge_oracle q0,q1,q2,q3,q4,q5,q6;
  s_operator_2_bitwise_swap q6,q0,q1,q2,q3,q4,q5;
}

qreg q[105];
main_hadamard_transform q[0],q[1],q[2];
main_c_operator_0 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37];
main_s_operator_0 q[0],q[1],q[2],q[3],q[4],q[5],q[38];
main_c_operator_1 q[0],q[1],q[2],q[3],q[4],q[5],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63],q[64],q[65],q[66],q[67],q[68],q[69],q[70];
main_s_operator_1 q[0],q[1],q[2],q[3],q[4],q[5],q[71];
main_c_operator_2 q[0],q[1],q[2],q[3],q[4],q[5],q[72],q[73],q[74],q[75],q[76],q[77],q[78],q[79],q[80],q[81],q[82],q[83],q[84],q[85],q[86],q[87],q[88],q[89],q[90],q[91],q[92],q[93],q[94],q[95],q[96],q[97],q[98],q[99],q[100],q[101],q[102],q[103];
main_s_operator_2 q[0],q[1],q[2],q[3],q[4],q[5],q[104];
