name: "Setup classiq nightly"
description: "setup python ; install classiq nighyly from aws ; install quenne ; setup M2M token"

defaults:
  run:
    shell: bash

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Propagate env-var for nightly
      run: |
        echo 'CLASSIQ_IDE="https://nightly.platform.classiq.io"' >> $GITHUB_ENV
        echo 'CLASSIQ_HOST="https://nightly.platform.classiq.io"' >> $GITHUB_ENV

    # Configure AWS credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: arn:aws:iam::392220832072:role/PublicGithubCIRole
        aws-region: us-east-1
        mask-aws-account-id: true

    - name: Install dependencies
      run: |
        set -e

        python -m pip install -U pip \
            --extra-index-url https://pypi.org/simple

        # Install "classiq" separately
        export CODEARTIFACT_AUTH_TOKEN="$(              \
            aws codeartifact get-authorization-token    \
            --domain ${{ secrets.CODEARTIFACT_DOMAIN }} \
            --domain-owner 392220832072                 \
            --region us-east-1                          \
            --query authorizationToken                  \
            --output text                               \
        )"
        python -m pip install -U --pre \
            --extra-index-url "https://aws:$CODEARTIFACT_AUTH_TOKEN@${{ secrets.CODEARTIFACT_DOMAIN }}-392220832072.d.codeartifact.us-east-1.amazonaws.com/pypi/Pypi-Classiq-Non-Prod/simple/" \
            --extra-index-url https://pypi.org/simple \
            classiq

        # Install everything from the requirements, other than "classiq".
        python -m pip install -U $(grep -ivE "classiq" requirements.txt) \
            --extra-index-url https://pypi.org/simple
        python -m pip install -U -r requirements_tests.txt \
            --extra-index-url https://pypi.org/simple

    - name: Install couenne solver
      env:
        COIN_DIST_URL: https://github.com/ampl/coin/releases/download/v20191215/coin-linux64.tar.gz
        LOCAL_BIN: ${{ runner.temp }}/.local/bin
      run: |
        set -eux
        mkdir -p "$LOCAL_BIN"
        echo "$LOCAL_BIN" >>"$GITHUB_PATH"
        wget -nv -O- "$COIN_DIST_URL" | tar -C "$RUNNER_TEMP" -xvz
        cp "${RUNNER_TEMP}/couenne" "${LOCAL_BIN}/couenne"
        chmod ugo+x "${LOCAL_BIN}/couenne"

    # Set authentication with M2M token
    - name: Set authentication
      shell: bash
      run: .github/scripts/get_m2m_token.sh
      env:
        IS_DEV: "true"
        M2M_SECRET_ARN: "${{ secrets.NIGHTLY_M2M_SECRET_ARN }}"
