name: "Test Notebooks Action"
description: "Runs tests on a list of notebooks based on the specified environment."

inputs:
  # diff files - set to python inside pytest
  should_test_all_files:
    description: "'true' / 'false'."
    required: true
  list_of_ipynb_changed:
    description: "The list of changed files."
    required: true
  # aws environemnt
  is_dev:
    description: "The secret for environment authentication."
    required: true
  m2m_secret_arn:
    description: "The secret for environment authentication."
    required: true
  aws_role:
    description: "The AWS role to assume for configuring credentials during the execution."
    required: true
  # environment
  classiq_ide:
    description: "The secret for environment authentication."
    required: true
  classiq_host:
    description: "The secret for environment authentication."
    required: true

runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ inputs.aws_role }}
        aws-region: us-east-1
        mask-aws-account-id: true

    - name: Set authentication
      run: .github/scripts/get_m2m_token.sh
      shell: bash
      env:
        IS_DEV: "${{ inputs.is_dev }}"
        M2M_SECRET_ARN: "${{ inputs.m2m_secret_arn }}"

    - name: Run Notebooks
      run: python -m pytest --log-cli-level=INFO tests
      env:
        JUPYTER_PLATFORM_DIRS: "1"
        SHOULD_TEST_ALL_FILES: "${{ inputs.should_test_all_files }}"
        LIST_OF_IPYNB_CHANGED: "${{ inputs.list_of_ipynb_changed }}"
        CLASSIQ_IDE: "${{ inputs.classiq_ide }}"
        CLASSIQ_HOST: "${{ inputs.classiq_host }}"

      shell: bash
