// Generated by Classiq.
// Classiq version: 0.0.0
// Creation timestamp: 2023-08-23T07:30:02.744736+00:00
// Random seed: 206755496

OPENQASM 2.0;
include "qelib1.inc";
gate r1tof q0,q1,q2 {
  h q2;
  t q2;
  cx q1,q2;
  tdg q2;
  cx q0,q2;
  t q2;
  cx q1,q2;
  tdg q2;
  h q2;
}

gate statepreparation_1_bellstatepreparation q0,q1 {
  x q1;
  h q0;
  cx q0,q1;
}

gate statepreparation_0_bellstatepreparation q0,q1 {
  h q0;
  cx q0,q1;
}

gate statepreparation_0 q0,q1 {
  statepreparation_0_bellstatepreparation q0,q1;
}

gate statepreparation_1 q0,q1 {
  statepreparation_1_bellstatepreparation q0,q1;
}

gate adder q0,q1,q2,q3,q4,q5,q6,q7 {
  cx q0,q4;
  cx q1,q5;
  cx q3,q5;
  cx q3,q7;
  r1tof q2,q4,q7;
  cx q3,q6;
  ccx q7,q5,q6;
  cx q7,q5;
  r1tof q2,q4,q7;
  cx q3,q7;
  cx q2,q4;
  cx q3,q5;
}

qreg q[8];
statepreparation_0 q[0],q[1];
statepreparation_1 q[2],q[3];
adder q[2],q[3],q[0],q[1],q[4],q[5],q[6],q[7];
