name: "Automatic Deployment"

on:
  pull_request:
    branches:
      - dev
      - CAD-23261
    types:
      - closed
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/deployment-qmod.yml
    with:
      deploy-mode: staging
    secrets: inherit
