name: "Automatic Deployment"

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-prod:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/deployment-qmod.yml
    with:
      deploy-mode: production
    secrets: inherit

  deploy-dev:
    if: github.ref_name == 'dev'
    uses: ./.github/workflows/deployment-qmod.yml
    with:
      deploy-mode: staging
    secrets: inherit
