name: PR Hello Workflow

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  hello_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello Nadav"
