name: "Test notebooks"

on: [pull_request, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Install dependencies"
        run: |
          python -m pip install -U -r requirements.txt
          python -m pip install -U -r requirements_tests.txt

      - name: "Run tests"
        run: python -m pytest tests
