name: "Test CI (weekly) (notebooks: algorithms)"

on:
  schedule:
    - cron: "00 04 * * 6" # Saturday, 04:00 UTC
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  nightly-test:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python and classiq and nightly aws
        uses: ./.github/actions/setup_classiq_on_nightly
        with:
          aws-role: ${{ secrets.AWS_ROLE }}
          codeartifact-domain: ${{ secrets.CODEARTIFACT_DOMAIN }}
          codeartifact-owner: ${{ secrets.CODEARTIFACT_OWNER }}
          codeartifact-region: ${{ secrets.CODEARTIFACT_REGION }}
          nightly-m2m-secret-arn: ${{ secrets.NIGHTLY_M2M_SECRET_ARN }}
          pypi-nightly-name: ${{ secrets.PYPI_NIGHTLY_NAME }}

      - name: Show file before
        id: cat-before
        run: |
          echo ===============
          echo "qmod before"
          echo ======
          cat algorithms/bernstein_vazirani/bernstein_vazirani_example.qmod

      # Run Notebook Tests
      - name: Run Notebooks
        run: python -m pytest tests/notebooks/test_bernstein_vazirani.py
        env:
          # to disable a warning in Jupyter notebooks
          JUPYTER_PLATFORM_DIRS: "1"
          # Passing which notebooks changed
          SHOULD_TEST_ALL_FILES: "true" # quick tests should run all files
          LIST_OF_IPYNB_CHANGED: "${{ steps.changed-files-ipynb.outputs.all_changed_files }}"
          LIST_OF_IPYNB_TESTS_CHANGED: "${{ steps.changed-files-tests.outputs.all_changed_files }}"
          # Passing environment information
          CLASSIQ_IDE: "https://nightly.platform.classiq.io"
          CLASSIQ_HOST: "https://nightly.platform.classiq.io"
          # Altering test behavior
          QMOD_COMPARISON_FIRST: "true"

      - name: Show file after
        if: ${{ always() }}
        id: cat-after
        run: |
          echo ===============
          echo "qmod after"
          echo ======
          cat algorithms/bernstein_vazirani/bernstein_vazirani_example.qmod
