name: "Test Library CI (main)"

# This workflow always run in the context of Classiq/classiq-library (base repo) but might use a branch from a fork to test its contribution
# PRs from users (should be from a fork) need to targePrint repository namet `main` branch which runs against `prod` environment

on:
  push: # Trigger the workflow on push to the specific branch
    branches:
      - main
  pull_request_target: # Trigger the workflow on pull requests targeting the specific branch
    # Note: `pull_request_target` ensures that the tests run in the context of the `main` branch, not in the user's fork.
    branches:
      - main

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the target branch
        id: checkout
        run: |
          echo 1111111
          df -h
          echo 2222222
          free -h
          echo 3333333
          mount
          echo 4444444
          pwd
          echo 5555555
          du -shc ~/* ~/.*
          echo 6666666
          df -h ~
          echo 7777777
